const Map<String, List<String>> citiesData = {
  "Libya": [
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Sebha",
    "Zawiya",
    "Zliten",
    "Al Bayda",
    "Ajdabiya",
    "Darna",
    "Sirte",
    "Sabratha",
    "Al Khums",
    "Al Marj",
    "Gharyan",
    "Tobruk",
    "Bani Walid",
    "Tarhuna",
    "Zuwara",
    "Ubari",
    "Kufra",
    "Hon",
    "Nalut",
    "Yafran",
    "Jalu",
    "Ghadames",
    "Brak Al-Shati",
    "Murzuq",
    "Tazirbu",
    "Qatrun",
    "Riqdalin",
    "Al-Ajilat",
    "Qara Buli",
    "Tokra",
    "Seluq",
    "Msallata",
  ],

  "Tunisia": [
    "Tunis",
    "Djerba",
    "Djerjis",
    "Ariana",
    "Ben Arous",
    "La Marsa",
    "Carthage",
    "Sfax",
    "Sousse",
    "Monastir",
    "Kairouan",
    "Mahdia",
    "Bizerte",
    "Nabeul",
    "Hammamet",
    "Zaghouan",
    "Jendouba",
    "El Kef",
    "Siliana",
    "Gabès",
    "Medenine",
    "Tataouine",
    "Kebili",
    "Tozeur",
    "Ramada",
    "Douz",
  ],

  "Egypt": [
    "Cairo",
    "Giza",
    "Alexandria",
    "Mansoura",
    "Tanta",
    "Asyut",
    "Zagazig",
    "Ismailia",
    "Suez",
    "Luxor",
    "Port Said",
    "El Mahalla El Kubra",
    "Minya",
    "Beni Suef",
    "Damanhur",
    "Qena",
    "Aswan",
    "Damietta",
    "Faiyum",
    "Kafr El Sheikh",
    "Shibin El Kom",
    "El Arish",
    "Marsa Matruh",
    "Hurghada",
    "Sharm El Sheikh",
    "6th of October City",
    "10th of Ramadan City",
    "Helwan",
    "Belbeis",
    "Nag Hammadi",
  ],

  "Algeria": [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Setif",
    "Batna",
    "Blida",
    "Tlemcen",
    "Bejaia",
    "Ouargla",
    "Chlef",
    "Sidi Bel Abbes",
    "Tizi Ouzou",
    "Biskra",
    "Mostaganem",
    "Laghouat",
    "Jijel",
    "Skikda",
    "Medea",
    "Ghardaia",
    "Bordj Bou Arreridj",
    "El Tarf",
    "Adrar",
    "Tamanrasset",
    "El Bayadh",
  ],
};
