import 'package:get/get.dart';

class AppLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'arabic': 'Arabic',
      'next': 'Next',
      'skip': 'Skip',
      'login': 'Login',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'coming_soon': 'Coming Soon',
      'change_password': 'Change Password',
      'notification': 'Notification',
      'rewards': 'Rewards',
      'log_out': 'Log out',
      'dark_theme': 'Dark Theme',
      'select_country': 'Select Country',
      'confirm_logout': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'clinic_manager_info': 'Clinic Manager Info',
      'manager_full_name': 'Manager Full Name',
      'manager_phone_number': 'Manager Phone Number',
      'clinic_logo': 'Clinic Logo',
      'upload_logo': 'Upload Logo',
      'clinic_name': 'Clinic Name',
      'enter_clinic_name': 'Enter your clinic name',
      'about_clinic': 'About Clinic',
      'enter_about_clinic': 'Enter about clinic',
      'contact_phone_number': 'Contact Phone Number',
      'enter_contact_phone': 'Enter contact phone number',
      'location_optional': 'Location (Optional)',
      'enter_location': 'Enter location',
      'contact_number': 'Contact Number',
      'submit_create_clinic': 'Submit & Create Clinic',
      'clinic_review_message':
          'Thank you. Your clinic account is\nnow under review',
      'clinic_review_desc':
          'Our team is reviewing your clinic details to keep Salama safe and trusted. Once approved, you\'ll be able to manage your doctors and appointments.',
      'submitted_information': 'Submitted Information',
      'ok_got_it': 'OK, got it!',
      'professional_info': 'Your Professional Info',
      'medical_specialty': 'Medical Specialty',
      'your_medical_specialty': 'Your Medical Specialty',
      'years_of_experience': 'Years of Experience',
      'enter_years_experience': 'Enter years of experience',
      'license_number_optional': 'License Number (Optional)',
      'enter_license_number': 'Enter medical license number',
      'base_consultation_fee': 'Base Consultation Fee',
      'enter_consultation_fee': 'Enter consultation fee',
      'clinic_info_optional': 'Clinic Information (Optional)',
      'select_clinic': 'Select Clinic',
      'select_clinic_info': 'Select clinic info',
      'complete_profile': 'Complete Your Profile',
      'select_gender': 'Select Gender',
      'select_your_gender': 'Select your gender',
      'select_your_country': 'Select your country',
      'select_city': 'Select City',
      'select_your_city': 'Select your city',
      'address_optional': 'Address (Optional)',
      'certification_message':
          'I certify that all provided information is accurate and correct.',
      'enter_referral_code_optional': 'Enter referral code (optional)',
      'can_skip_step': 'You can skip this step.',
      'referral_code': 'Referral Code',
      'error_fill_fields':
          'Please fill all required fields and certify the information',
      'profile_info': 'Profile Info',
      'refer': 'Refer',
      'insurance': 'Insurance',
      'country': 'Country',
      'help_center': 'Help Center',
      'legal_and_policies': 'Legal and Policies',
      'send_feedback': 'Send your Feedback',
      'change_country': 'Change Country',
      'full_name': 'Full Name',
      'gender': 'Gender',
      'date_of_birth': 'Date of Birth',
      'city': 'City',
      'address_details': 'Address Details',
      'male': 'Male',
      'patient': 'Patient',
      'libya': 'Libya',
      'egypt': 'Egypt',
      'syria': 'Syria',
      'algeria': 'Algeria',
      'enter_full_name': 'Enter Full Name',
      'select_date_of_birth': 'Select your date of birth',
      'address': 'Address',
      'enter_address': 'Enter your address',
      'save_change': 'Save Change',
      'female': 'Female',
      'riyadh': 'Riyadh',
      'jeddah': 'Jeddah',
      'dammam': 'Dammam',
      'success': 'Success',
      'error': 'Error',
      'profile_updated_success': 'Profile updated successfully',
      'referral_code_submitted': 'Referral code submitted (or skipped)',
      'slogan': 'Your Trusted Medical Partner',
      'phone_number': 'Phone Number',
      'enter_phone_number': 'Enter your phone number',
      'digits': 'digits',
      'choose_code_method': 'Choose how to receive your code',
      'whatsapp': 'WhatsApp',
      'sms_code': 'SMS code',
      'continue': 'Continue',
      'tunisia': 'Tunisia',
      'please_enter_phone': 'Please enter your phone number',
      'phone_9_digits': 'Phone number must be 9 digits',
      'phone_8_digits': 'Phone number must be 8 digits',
      'phone_10_digits': 'Phone number must be 10 digits',
      'phone_min_8_digits': 'Phone number must be at least 8 digits',
      'invalid_provider_libya':
          'Invalid provider code (must start with 91, 92, 93, 94, 95)',
      'invalid_provider_egypt':
          'Invalid provider code (must start with 10, 11, 12, 15)',
      'invalid_provider_algeria':
          'Invalid provider code (must start with 5, 6, 7)',
      'invalid_provider_bangladesh':
          'Invalid provider code for Bangladesh (must start with 1)',
      'enter_verification_code': 'Enter Verification Code',
      'verification_code_message':
          'You will receive a WhatsApp message with a verification pin on',
      'didnt_receive_code': 'Didn’t receive code?  ',
      'resend': 'Resend',
      'resend_code_in': 'Resend Code in',
      'submit': 'Submit',
      'enter_6_digits': 'Please enter all 6 digits',
      'choose_your_role': 'Choose Your Role',
      'role_selection_subtitle':
          'Identify the user’s role before continuing to profile setup.',
      'doctor': 'Doctor',
      'clinic': 'Clinic',
      'faq': 'FAQ',
      'who_is_salama': 'Who is Salama?',
      'who_is_salama_desc':
          'Salama is a comprehensive healthcare platform that connects patients with qualified doctors for consultations and medical services.',
      'doctor_consultation_title': 'What is a doctor consultation?',
      'doctor_consultation_desc':
          'A doctor consultation is a professional medical appointment where you can discuss your health concerns, receive diagnosis, and get treatment recommendations from qualified healthcare providers.',
      'Libya': 'Libya',
      'Tunisia': 'Tunisia',
      'Egypt': 'Egypt',
      'Algeria': 'Algeria',
      'bangladesh': 'Bangladesh',
      'Syria': 'Syria',
      'schedule_appointment_title': 'How do I schedule an appointment?',
      'schedule_appointment_desc':
          'You can schedule an appointment by browsing available doctors, selecting your preferred time slot, and confirming your booking through the app.',
      'payment_options_title': 'What are the payment options?',
      'payment_options_desc':
          'We accept various payment methods including credit cards, debit cards, and mobile payment options for your convenience.',
      'cancel_reschedule_title': 'How can I cancel or reschedule?',
      'cancel_reschedule_desc':
          'You can cancel or reschedule your appointment from the appointments section. Please note our cancellation policy for any applicable fees.',
      'referral_program': 'Referral Program',
      'referral_program_desc': 'Invite friends and earn 1 LYD for each signup!',
      'your_referral_code': 'Your Referral Code',
      'friends_invited': 'Friends Invited',
      'total_earned': 'Total Earned',
      'terms': 'Terms',
      'terms_content':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      'changes_policies': 'Changes to the Service and/or Terms:',
      'changes_policies_content':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
      'find_doctors_hint': 'Find doctors, clinics, specialties...',
      'health_ai_assistant': 'Health AI Assistant',
      'could_not_open_email': 'Could not open email app.',
      'ai_assistant_desc': 'Ask anything about symptoms, doctors or clinics.',
      'ambulance': 'Ambulance',
      'pharmacy': 'Pharmacy',
      'consultation': 'Consultation',
      'popular_doctors': 'Popular Doctors',
      'view_all': 'View all',
      'nearby_clinics': 'Nearby Clinics',
      'year_exp': 'y exp',
      'years_exp': 'Years Experience',
      'neurologist': 'Neurologist',
      'specialties_count': 'Specialties',
      'search': 'Search',
      'book': 'Book',
      'lyd': 'LYD',
      'home': 'Home',
      'appointment': 'Appointment',
      'wallet': 'Wallet',
      'my_wallet': 'My Wallet',
      'recent_transactions': 'Recent Transactions',
      'current_balance': 'Current Balance',
      'balance_desc': 'Use your balance to pay for appointments.',
      'top_up_wallet': 'Top Up Wallet',
      'my_appointment': 'My Appointment',
      'queue': 'Queue',
      'review': 'Review',
      'your_review': 'Your Review',
      'doctor_details': 'Doctor Details',
      'year_of_work': 'Year of work',
      'rating': 'Rating',
      'per_session': 'Per Session',
      'view_full_timings': 'View Full Timings',
      'about_doctor': 'About Doctor',
      'book_appointment': 'Book Appointment',
      'schedule': 'Schedule',
      'day': 'Day',
      'time': 'Time',
      'to': 'to',
      'sunday': 'Sunday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'choose_time_slot': 'Choose a time slot',
      'select_date_schedule_desc':
          'Please select an available date or schedule to conduct a consultation',
      'select_date': 'Select Date',
      'available_time': 'Available Time',
      'booking_confirmation': 'Booking Confirmation',
      'booking_success_desc':
          'Payment for your successful doctor\'s appointment, please come based on the agreed schedule',
      'back_to_home': 'Back to Home',
      'confirm_booking': 'Confirm Booking',
      'date_time': 'Date & Time',
      'session_fee': 'Session Fee',
      'queue_number': 'Queue number',
      'payment': 'Payment',
      'confirm_and_pay': 'Confirm',
      'select': 'Select',
      'not_selected': 'Not Selected',
      'no_schedule_available': 'No schedule available',
      'schedule_today': "Today's Schedule",
      'no_bio_available': 'No bio available',
      'no_appointments_found': 'No appointments found',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      'jul': 'Jul',
      'aug': 'Aug',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'clinic_details': 'Clinic Details',
      'info': 'Info',
      'read_more': 'Read More',
      'contact': 'Contact',
      'filter': 'Filter',
      'reset_filters': 'Reset Filters',
      'availability': 'Availability',
      'price_range': 'Price Range (per visit)',
      'insurance_accepted': 'Insurance Accepted',
      'minimum_rating': 'Minimum Rating',
      'clear_all': 'Clear All',
      'apply_filters': 'Apply Filters',
      'most_popular_specialties': 'Most Popular Specialties',
      'results': 'Results',
      'specialty': 'Specialty',
      'withdraw': 'Withdraw',
      'welcome': 'Welcome',
      'welcome_user': 'Welcome, @name',
      'total_book': 'Total Book',
      'today': 'Today',
      'upcoming': 'Upcoming',
      'todays_appointments': "Today's Appointments",
      'arrived': 'Arrived',
      'completed': 'Completed',
      'finished': 'Finished',
      'no_appointments': 'No appointments',
      'notifications': 'Notifications',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'confirm': 'Confirm',
      'update_status': 'Update Status',
      'clinic_info': 'Clinic Info',
      'available_times': 'Available Times',
      'select_bank': 'Select Bank',
      'years': 'Years',
      'license_number': 'License Number',
      'sar': 'SAR',
      'enter_address_details': 'Enter Address Details',
      'enter_specialty': 'Enter Specialty',
      'enter_years_of_experience': 'Enter Years of Experience',
      'enter_fee': 'Enter Fee',
      'your_doctor_specialty': 'Your Doctor Specialty',
      'tripoli': 'Tripoli',
      'benghazi': 'Benghazi',
      'misrata': 'Misrata',
      'bank_of_libya': 'Bank of Libya',
      'clinic_information': 'Clinic Information',
      'working_hours': 'Working Hours',
      'location': 'Location',
      'na': 'N/A',
      'no_data_found': 'No data found',
      'no_clinics_found': 'No clinics found',
      'joined_since': 'Joined Since',
      'joined_on': 'Joined on',
      'specialists': 'Specialists',
      'change_clinic': 'Change Clinic',
      'choose_a_clinic': 'Choose a Clinic',
      'set_your_availability': 'Set Your Availability',
      'select_working_days': 'Select Working Days',
      'set_time_slots': 'Set Time Slots',
      'capacity': 'Capacity',
      'add_more': 'Add More',
      'need_more_help': 'Need More Help?',
      'support_team_desc':
          "Can't find what you're looking for? Our support team is here to help.",
      'email': 'Email',
      'enter_email': 'Enter your email',
      'who_is_nabeel': 'Who is nabeelaljirbi?',
      'who_is_nabeel_desc':
          'Nabeel Aljirbi is a comprehensive healthcare platform that connects patients with qualified doctors for consultations and medical services.',
      'doctors': 'Doctors',
      'copied': 'Copied',
      'referral_code_copied': 'Referral code copied to clipboard',
      'consultation_fee': 'Consultation Fee',
      'referral_bonus': 'Referral Bonus',
      'filter_by_doctor': 'Filter by Doctor',
      'all_doctors': 'All Doctors',
      'queue_label': 'Queue #',
      'new_appointment_booked': 'New Appointment Booked',
      'upcoming_appointment_title': 'Upcoming Appointment',
      'appointments': 'Appointments',
      'pending_tab': 'Pending',
      'in_progress_tab': 'In Progress',
      'completed_tab': 'Completed',
      'arrived_tab': 'Arrived',
      'confirmed': 'Confirmed',
      'inprogress': 'In Progress',
      'cancelled': 'Cancelled',
      'not_shown': 'Not Shown',
      'unresolved': 'Unresolved',
      'not_updated': 'Not Updated',
      'cancel_appointment_title': 'Cancel Appointment',
      'cancel_appointment_message':
          'Are you sure you want to cancel this appointment?',
      'yes_cancel': 'Yes, Cancel',
      'update_status_title': 'Update Status',
      'update_status_arrived_message':
          'Do you want to update the status to Arrived?',
      'yes_update': 'Yes, Update',
      'complete_appointment_title': 'Complete Appointment',
      'complete_appointment_message':
          'Do you want to update the status to Completed?',
      'yes_complete': 'Yes, Complete',
      'complete': 'Complete',
      'status_updated_successfully': 'Status updated successfully',
      'failed_to_update_status': 'Failed to update status',
      'load_more': 'Load More',
      'show_less': 'Show Less',
      'photos': 'Photos',
      'manager_name': 'Manager Name',
      'manager_number': 'Manager Number',
      'clinic_number': 'Clinic Number',
      'edit_clinic_info': 'Edit Clinic Info',
      'add_photo': 'Add Photo',
      'referred': 'Referred',
      'total_with_count': 'Total (@count)',
      'referral_desc_clinic':
          'Invite other clinics or patients and earn 50 LYD for each successful referral!',
      'terms_clinic_title': 'Terms of Service for Clinics',
      'terms_clinic_content':
          'By joining Salama as a clinic partner, you agree to provide accurate information about your services, doctors, and availability. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_clinic_desc':
          'We value your privacy and the privacy of your patients. Please refer to our main privacy policy for details on how we collect, use, and protect data within the platform.',
      'delete_specialty': 'Delete Specialty',
      'delete_specialty_confirmation':
          'Are you sure you want to remove this specialty?',
      'delete': 'Delete',
      'add_specialty': 'Add Specialty',
      'search_specialty': 'Search specialty',
      'clinic_updated_success': 'Clinic info updated successfully',
      'dermatology': 'Dermatology',
      'dentistry': 'Dentistry',
      'psychiatry': 'Psychiatry',
      'pediatrics': 'Pediatrics',
      'psychotherapy': 'Psychotherapy',
      'neurology': 'Neurology',
      'orthopedics': 'Orthopedics',
      'obstetrics': 'Obstetrics and Genecology',
      'ear_nose_throat': 'Ear, Nose and Throat',
      'cardiology': 'Cardiology and Vascular Disease',
      'general_surgery': 'General Surgery',
      'ophthalmology': 'Ophthalmology',
      'urology': 'Urology',
      'about_clinic_desc':
          'Our clinic is committed to providing reliable, high-quality healthcare services with a patient-first approach. We focus on accurate diagnosis, modern treatment, and compassionate care to ensure the best experience for every patient.',
      'search_doctor': 'Search doctor...',
      'all_specialties': 'All Specialties',
      'all_insurance': 'All Insurance',
      'all_cities': 'All Cities',
      'all_countries': 'All Countries',
      'confirm_appointment_title': 'Confirm Appointment',
      'confirm_appointment_message':
          'Are you sure you want to confirm this appointment?',
      'inprogress_appointment_title': 'Start Appointment',
      'inprogress_appointment_message':
          'Are you sure you want to mark this appointment as in progress?',
      'save_changes': 'Save Changes',
      'select_working_day': 'Select Working Day',
      'no_insurance_found': 'No insurance found',
      'add_insurance': 'Add Insurance',
      'insurance_details': 'Insurance Details',
      'upload_insurance_image': 'Upload Insurance Image',
      'failed_to_fetch_working_hours': 'Failed to fetch working hours',
      'error_fetching_working_hours':
          'An error occurred while fetching working hours',
      'working_hours_saved_successfully': 'Working hours saved successfully',
      'failed_to_save_working_hours': 'Failed to save working hours',
      'error_occurred_while_saving': 'An error occurred while saving',
      'Feature coming soon': 'Feature coming soon',
      'cancel_appointment': 'Cancel Appointment',
      'are_you_sure_cancel':
          'Are you sure you want to cancel this appointment?',
      'no': 'No',
      'please_select_rating': 'Please select a rating',
      'review_submitted_successfully': 'Review submitted successfully',
      'failed_to_submit_review': 'Failed to submit review',
      'error_occurred': 'An error occurred',
      'appointment_cancelled_successfully':
          'Appointment cancelled successfully',
      'failed_to_cancel_appointment': 'Failed to cancel appointment',
      'cancel_appointment_confirmation':
          'Are you sure you want to cancel this appointment?',
      'yes_confirm': 'Yes, Confirm',
      'mark_as_arrived': 'Mark as Arrived',
      'confirm_arrival_message':
          'Are you sure you want to mark this appointment as arrived?',
      'ive_arrived': "I've Arrived",
      'complete_appointment': 'Complete Appointment',
      'confirm_complete_message':
          'Are you sure you want to mark this appointment as complete?',
      'appointment_status_updated': 'Appointment status updated successfully',
      'consultation_with': 'Consultation w/',
      'unknown_doctor': 'Unknown Doctor',
      'no_details_found': 'No details found',
      'doctor_id_missing': 'Doctor ID is missing',
      'failed_to_load_doctor_details': 'Failed to load doctor details',
      'server_error': 'Server error',
      'all': 'All',
      'experience': 'Experience',
      '1_3_years': '1-3 years',
      '3_5_years': '3-5 years',
      '5_10_years': '5-10 years',
      '10_plus_years': '10+ years',
      'cardiologist': 'Cardiologist',
      'dentist': 'Dentist',
      'orthopedic': 'Orthopedic',
      'total': 'Total',
      'about': 'About',
      'specialties': 'Specialties',
      'no_specialists_found': 'No specialists found',
      'add_specialist': 'Add Specialist',
      'enter_specialist_details': 'Enter specialist details',
      'please_select_image': 'Please select an image',
      'please_enter_details': 'Please enter details',
      'specialist_added_success': 'Specialist added successfully',
      'failed_to_add_specialist': 'Failed to add specialist',
      'something_went_wrong': 'Something went wrong',
      'no_photos_yet': 'No photos yet',
      'add_photos': 'Add Photos',
      'delete_photos': 'Delete Photos',
      'photos_uploaded_successfully': 'Photos uploaded successfully',
      'failed_to_upload_photos': 'Failed to upload photos',
      'photos_deleted_successfully': 'Photos deleted successfully',
      'failed_to_delete_photos': 'Failed to delete photos',
      'clinic_photos': 'Clinic Photos',
      'please_enter_insurance_details': 'Please enter insurance details',
      'please_select_an_image': 'Please select an image',
      'insurance_added_successfully': 'Insurance added successfully',
      'failed_to_add_insurance': 'Failed to add insurance',
      'select_insurance': 'Select Insurance',
      'delete_insurance': 'Delete Insurance',
      'delete_insurance_confirmation':
          'Are you sure you want to delete this insurance?',
      'insurance_deleted_successfully': 'Insurance deleted successfully',
      'failed_to_delete_insurance': 'Failed to delete insurance',
      'select_specialty': 'Select Specialty',
      'specialist_deleted_success': 'Specialist deleted successfully',
      'failed_to_delete_specialist': 'Failed to delete specialist',
      'failed_to_fetch_specialists': 'Failed to fetch specialists',
      'please_select_city': 'Please select a city',
      'profile_updated_successfully': 'Profile updated successfully',
      'failed_to_update_profile': 'Failed to update profile',
      'failed_to_update_clinic': 'Failed to update clinic info',
      'remove_doctor': 'Remove Doctor',
      'are_you_sure_remove_doctor':
          'Are you sure you want to remove this doctor from your clinic?',
      'doctor_removed_successfully': 'Doctor removed successfully',
      'failed_to_remove_doctor': 'Failed to remove doctor',
      'could_not_remove_doctor_id_missing':
          'Could not remove doctor, ID is missing.',
      'appointment_confirmed_successfully':
          'Appointment confirmed successfully',
      'failed_to_confirm_appointment': 'Failed to confirm appointment',
      'location_permission_title': 'Location Permission',
      'location_permission_message':
          'We need your location to show clinics and doctors near you. Please allow location access in the next popup.',
      'allow': 'Allow',
      'deny': 'Deny',
      'notification_permission_message':
          'We need permission to send you notifications for appointments and updates.',
      'app_name': 'Salama',
      'unknown': 'Unknown',
      'available': 'Available',
      'location_info_unavailable': 'Location info unavailable',
      'from': 'from',
      'search_result': 'Search Result',
      'book_now': 'Book Now',
      'closed': 'Closed',
      'am': 'AM',
      'pm': 'PM',
      'km': 'km',
      'no_doctors_available': 'No doctors available',
      'no_insurance_data': 'No Insurance Data',
      'not_available': 'N/A',
      'no_doctors_found': 'No doctors found',
      'managing_appointments_title': 'Managing Appointments',
      'managing_appointments_desc':
          'Doctors can view incoming appointments, accept or reschedule them, and update their status (pending, in-progress, completed) directly from the dashboard.',
      'update_profile_title': 'Update Profile',
      'update_profile_desc':
          'Keep your profile updated with your latest specialties, experience, and consultation fees to attract more patients.',
      'payments_title': 'Payments & Wallet',
      'payments_desc':
          'Track your earnings and view transaction history in the Wallet section. Payments are processed securely.',
      'technical_support_title': 'Technical Support',
      'technical_support_desc':
          'For any app-related issues or account assistance, please contact our support team via email.',
      'doctor_terms_title': 'Doctor Terms of Service',
      'doctor_terms_content':
          'By registering as a doctor on Salama, you agree to provide accurate medical advice, maintain patient confidentiality, and adhere to our professional conduct guidelines. You are responsible for managing your schedule and appointments efficiently.',
      'doctor_privacy_policy': 'Doctor Privacy Policy',
      'doctor_privacy_policy_desc':
          'We collect and process your professional data to connect you with patients. Patient medical records are strictly confidential and shared only for consultation purposes.',
      'how_to_book_title': 'How to Book an Appointment',
      'how_to_book_desc':
          'Search for a doctor or clinic by specialty or location, choose an available time slot, and confirm your booking instantly.',
      'my_appointments_help_title': 'My Appointments & History',
      'my_appointments_help_desc':
          'View your upcoming and past appointments in the "My Appointments" tab. You can check the status and details of each visit.',
      'patient_profile_help_title': 'Updating Personal Info',
      'patient_profile_help_desc':
          'Go to your Profile to update your personal details, medical history, and insurance information to keep your records current.',
      'patient_support_title': 'Patient Support',
      'patient_support_desc':
          'Need help? Contact our support team for assistance with bookings, payments, or app issues.',
      'patient_terms_title': 'Patient Terms of Service',
      'patient_terms_content':
          'By using Salama as a patient, you agree to provide accurate health information and adhere to our booking and cancellation policies. We are committed to connecting you with verified healthcare providers.',
      'patient_privacy_policy': 'Patient Privacy Policy',
      'patient_privacy_policy_desc':
          'Your health data is sensitive and treated with the highest level of security. We only share necessary information with doctors you book appointments with.',
      'managing_doctors_title': 'Managing Doctors',
      'managing_doctors_desc':
          'Add, remove, or update doctor profiles within your clinic. Ensure their specialties and schedules are accurate for patient bookings.',
      'clinic_appointments_help_title': 'Clinic Appointments',
      'clinic_appointments_help_desc':
          'View and manage all appointments across your clinic doctors from a centralized dashboard.',
      'clinic_profile_update_title': 'Updating Clinic Info',
      'clinic_profile_update_desc':
          'Keep your clinic details, such as location, contact info, and photos, up to date to attract more patients.',
      'clinic_payments_help_title': 'Financials & Payouts',
      'clinic_payments_help_desc':
          'Monitor your clinic\'s earnings and payouts securely through the dedicated wallet section.',
      'no_notifications_found': 'No notifications found',
      'new_appointment_desc': '@name booked an appointment for @date @time',
      'upcoming_appointment_desc':
          'You have an appointment with @name @time_diff',
      'in_minutes': 'in @min minutes',
      'tomorrow_low': 'tomorrow',
      'today_low': 'today',
      'ai_chat_title': 'Salama Ai',
      'hi_im_your': 'Hi, I\'m Your ',
      'medical': ' Medical',
      'assistant_excl': 'Assistant!',
      'ai_welcome_desc':
          'I can help you understand your symptoms and recommend the right specialist. What symptoms are you experiencing?',
      'medical_disclaimer':
          'Medical Disclaimer: Please consult a healthcare professional for medical advice, diagnosis, or treatment. Salama AI is for informational purposes only.',
      'ask': 'Ask',
      'describe_symptoms_hint': 'Describe your symptoms briefly...',
      'clinics': 'Clinics',
      'distance_away': 'km away',
      'limit_complete_message': 'Limit is complete for today',
      // Specialties
      'Dermatology': 'Dermatology',
      'Dentistry': 'Dentistry',
      'Psychiatry': 'Psychiatry',
      'Pediatrics': 'Pediatrics',
      'Psychotherapy': 'Psychotherapy',
      'Neurology': 'Neurology',
      'Orthopedics': 'Orthopedics',
      'Obstetrics and Genecology': 'Obstetrics and Genecology',
      'Ear, Nose and Throat': 'Ear, Nose and Throat',
      'Cardiology and Vascular Disease': 'Cardiology and Vascular Disease',
      // Insurances
      'LIBYA INSURANCE co.': 'LIBYA INSURANCE co.',
      'Al Madar': 'Al Madar',
      'Takaful': 'Takaful',
      'service_fee': 'Service Fee',
      // Cities - Libya
      'Tripoli': 'Tripoli',
      'Janzour': 'Janzour',
      'Tajura': 'Tajura',
      'Qasr bin Ghashir': 'Qasr bin Ghashir',
      'Benghazi': 'Benghazi',
      'Sidi Khalifa': 'Sidi Khalifa',
      'Al Marj': 'Al Marj',
      'Al Qubbah': 'Al Qubbah',
      'Misrata': 'Misrata',
      'Zliten': 'Zliten',
      'Harawa': 'Harawa',
      'Hun': 'Hun',
      'Waddan': 'Waddan',
      'Sokna': 'Sokna',
      'Sirte': 'Sirte',
      'Bin Jawad': 'Bin Jawad',
      'Nofaliya': 'Nofaliya',
      'Sabha': 'Sabha',
      'Murzuq': 'Murzuq',
      'Brak': 'Brak',
      'Al Kufra': 'Al Kufra',
      'Tazirbu': 'Tazirbu',
      'Jalu': 'Jalu',
      'Derna': 'Derna',
      'Al Bayda': 'Al Bayda',
      'Shahhat': 'Shahhat',
      'Tobruk': 'Tobruk',
      'El Gubba': 'El Gubba',
      'Khoms': 'Khoms',
      'El Hani': 'El Hani',
      'Ajdabiya': 'Ajdabiya',
      'Brega': 'Brega',
      'Marawa': 'Marawa',
      'Gharyan': 'Gharyan',
      'Yefren': 'Yefren',
      'Mizda': 'Mizda',
      'Zuwara': 'Zuwara',
      'Nalut': 'Nalut',
      'Ghadames': 'Ghadames',
      'Ghat': 'Ghat',
      'Ubari': 'Ubari',
      'Sebha': 'Sebha',
      'Zawiya': 'Zawiya',
      'Al Khums': 'Al Khums',
      'Sabratha': 'Sabratha',
      'Bani Walid': 'Bani Walid',
      'Tarhuna': 'Tarhuna',
      'Kufra': 'Kufra',
      'Hon': 'Hon',
      'Yafran': 'Yafran',
      'Brak Al-Shati': 'Brak Al-Shati',
      'Qatrun': 'Qatrun',
      'Riqdalin': 'Riqdalin',
      'Al-Ajilat': 'Al-Ajilat',
      'Qara Buli': 'Qara Buli',
      'Tokra': 'Tokra',
      'Seluq': 'Seluq',
      'Msallata': 'Msallata',
      // Cities - Tunisia
      'Ariana': 'Ariana',
      'La Soukra': 'La Soukra',
      'Ezzahra': 'Ezzahra',
      'Raoued': 'Raoued',
      'Beja': 'Beja',
      'Testour': 'Testour',
      'Nefza': 'Nefza',
      'Tibar': 'Tibar',
      'Ben Arous': 'Ben Arous',
      'Hammam Lif': 'Hammam Lif',
      'Rades': 'Rades',
      'Mornag': 'Mornag',
      'Boumhel': 'Boumhel',
      'Bizerte': 'Bizerte',
      'Menzel Bourguiba': 'Menzel Bourguiba',
      'Ras Jebel': 'Ras Jebel',
      'Sejnane': 'Sejnane',
      'Gabes': 'Gabes',
      'Matmata': 'Matmata',
      'Medenine': 'Medenine',
      'El Hamma': 'El Hamma',
      'Gafsa': 'Gafsa',
      'Metlaoui': 'Metlaoui',
      'Redeyef': 'Redeyef',
      'Mdhilla': 'Mdhilla',
      'Jendouba': 'Jendouba',
      'Aïn Draham': 'Aïn Draham',
      'Ghardimaou': 'Ghardimaou',
      'Tabarka': 'Tabarka',
      'Kairouan': 'Kairouan',
      'Chebika': 'Chebika',
      'Haffouz': 'Haffouz',
      'Sbikha': 'Sbikha',
      'Kasserine': 'Kasserine',
      'Sbeitla': 'Sbeitla',
      'Thala': 'Thala',
      'Foussana': 'Foussana',
      'Kebili': 'Kebili',
      'Douz': 'Douz',
      'El Faouar': 'El Faouar',
      'Mahdia': 'Mahdia',
      'Chebba': 'Chebba',
      'Ksour Essef': 'Ksour Essef',
      'El Jem': 'El Jem',
      'Manouba': 'Manouba',
      'Mornaguia': 'Mornaguia',
      'Borj El Amri': 'Borj El Amri',
      'Zarzis': 'Zarzis',
      'Ben Gardane': 'Ben Gardane',
      'Houmt Souk': 'Houmt Souk',
      'Monastir': 'Monastir',
      'Sahline': 'Sahline',
      'Moknine': 'Moknine',
      'Bekalta': 'Bekalta',
      'Nabeul': 'Nabeul',
      'Hammamet': 'Hammamet',
      'Korba': 'Korba',
      'Kelibia': 'Kelibia',
      'Sfax': 'Sfax',
      'Skhira': 'Skhira',
      'Thyna': 'Thyna',
      'El Ain': 'El Ain',
      'Sidi Bouzid': 'Sidi Bouzid',
      'Regueb': 'Regueb',
      'Meknassy': 'Meknassy',
      'Bir El Hafey': 'Bir El Hafey',
      'Siliana': 'Siliana',
      'Bouarada': 'Bouarada',
      'Kesra': 'Kesra',
      'Gaafour': 'Gaafour',
      'Sousse': 'Sousse',
      'Hammam Sousse': 'Hammam Sousse',
      'Enfidha': 'Enfidha',
      'Akouda': 'Akouda',
      'Tataouine': 'Tataouine',
      'Dehiba': 'Dehiba',
      'Bir Lahmar': 'Bir Lahmar',
      'Tozeur': 'Tozeur',
      'Degache': 'Degache',
      'Hazoua': 'Hazoua',
      'Tunis': 'Tunis',
      'La Marsa': 'La Marsa',
      'Le Kram': 'Le Kram',
      'Carthage': 'Carthage',
      'El Menzah': 'El Menzah',
      'Sidi Bou Said': 'Sidi Bou Said',
      'Zaghouan': 'Zaghouan',
      'Nadhour': 'Nadhour',
      'Bir Mcherga': 'Bir Mcherga',
      'Fahs': 'Fahs',
      'Djerba': 'Djerba',
      'Djerjis': 'Djerjis',
      'El Kef': 'El Kef',
      'Gabès': 'Gabès',
      'Ramada': 'Ramada',

      // Cities - Egypt
      'Cairo': 'Cairo',
      'New Cairo': 'New Cairo',
      'Nasr City': 'Nasr City',
      'Heliopolis': 'Heliopolis',
      'Maadi': 'Maadi',
      'Shubra': 'Shubra',
      'Helwan': 'Helwan',
      'Ain Shams': 'Ain Shams',
      'Mokattam': 'Mokattam',
      'Giza': 'Giza',
      '6th of October': '6th of October',
      'Sheikh Zayed': 'Sheikh Zayed',
      'Hawamdeya': 'Hawamdeya',
      'Al Ayyat': 'Al Ayyat',
      'Saf': 'Saf',
      'Abu Nomros': 'Abu Nomros',
      'Alexandria': 'Alexandria',
      'Borg El Arab': 'Borg El Arab',
      'New Borg El Arab': 'New Borg El Arab',
      'Amreya': 'Amreya',
      'Montaza': 'Montaza',
      'Mansoura': 'Mansoura',
      'Talkha': 'Talkha',
      'Mit Ghamr': 'Mit Ghamr',
      'Dikirnis': 'Dikirnis',
      'Belqas': 'Belqas',
      'Sherbin': 'Sherbin',
      'Hurghada': 'Hurghada',
      'Safaga': 'Safaga',
      'Quseir': 'Quseir',
      'Marsa Alam': 'Marsa Alam',
      'Ras Ghareb': 'Ras Ghareb',
      'Damanhur': 'Damanhur',
      'Kafr El Dawwar': 'Kafr El Dawwar',
      'Rashid (Rosetta)': 'Rashid (Rosetta)',
      'Abu Hummus': 'Abu Hummus',
      'Edku': 'Edku',
      'Fayoum': 'Fayoum',
      'Senours': 'Senours',
      'Etsa': 'Etsa',
      'Tamiya': 'Tamiya',
      'Tanta': 'Tanta',
      'El Mahalla El Kubra': 'El Mahalla El Kubra',
      'Zefta': 'Zefta',
      'Kafr El Zayat': 'Kafr El Zayat',
      'Samanoud': 'Samanoud',
      'Ismailia': 'Ismailia',
      'Fayed': 'Fayed',
      'Qantara East': 'Qantara East',
      'Qantara West': 'Qantara West',
      'Shibin El Kom': 'Shibin El Kom',
      'Sadat City': 'Sadat City',
      'Menouf': 'Menouf',
      'Ashmoun': 'Ashmoun',
      'Quesna': 'Quesna',
      'Minya': 'Minya',
      'Mallawi': 'Mallawi',
      'Samalut': 'Samalut',
      'Beni Mazar': 'Beni Mazar',
      'Maghagha': 'Maghagha',
      'Banha': 'Banha',
      'Qalyub': 'Qalyub',
      'Shubra El Kheima': 'Shubra El Kheima',
      'El Khanka': 'El Khanka',
      'Kafr Shukr': 'Kafr Shukr',
      'Kharga': 'Kharga',
      'Dakhla': 'Dakhla',
      'Farafra': 'Farafra',
      'Balat': 'Balat',
      'Suez': 'Suez',
      'Arbaeen': 'Arbaeen',
      'Faisal': 'Faisal',
      'Aswan': 'Aswan',
      'Kom Ombo': 'Kom Ombo',
      'Edfu': 'Edfu',
      'Darna': 'Darna',
      'Assiut': 'Assiut',
      'Dairut': 'Dairut',
      'Manfalut': 'Manfalut',
      'Abnub': 'Abnub',
      'Abu Tig': 'Abu Tig',
      'Beni Suef': 'Beni Suef',
      'Nasser': 'Nasser',
      'Ehnasia': 'Ehnasia',
      'Al Fashn': 'Al Fashn',
      'Biba': 'Biba',
      'Port Said': 'Port Said',
      'Port Fouad': 'Port Fouad',
      'Damietta': 'Damietta',
      'New Damietta': 'New Damietta',
      'Ras El Bar': 'Ras El Bar',
      'Faraskur': 'Faraskur',
      'Zagazig': 'Zagazig',
      '10th of Ramadan': '10th of Ramadan',
      'Belbeis': 'Belbeis',
      'Abu Kabir': 'Abu Kabir',
      'Minya Al Qamh': 'Minya Al Qamh',
      'Hehia': 'Hehia',
      'Sharm El Sheikh': 'Sharm El Sheikh',
      'Dahab': 'Dahab',
      'Nuweiba': 'Nuweiba',
      'Taba': 'Taba',
      'El Tor': 'El Tor',
      'Kafr El Sheikh': 'Kafr El Sheikh',
      'Desouk': 'Desouk',
      'Baltim': 'Baltim',
      'Sidi Salem': 'Sidi Salem',
      'Fuwa': 'Fuwa',
      'Marsa Matruh': 'Marsa Matruh',
      'El Alamein': 'El Alamein',
      'Siwa': 'Siwa',
      'Sallum': 'Sallum',
      'Dabaa': 'Dabaa',
      'Luxor': 'Luxor',
      'Esna': 'Esna',
      'Armant': 'Armant',
      'Toud': 'Toud',
      'Qena': 'Qena',
      'Nag Hammadi': 'Nag Hammadi',
      'Qift': 'Qift',
      'Naqada': 'Naqada',
      'Dishna': 'Dishna',
      'Abu Tesht': 'Abu Tesht',
      'El Arish': 'El Arish',
      'Sheikh Zuweid': 'Sheikh Zuweid',
      'Rafah': 'Rafah',
      'Bir Al Abd': 'Bir Al Abd',
      'Sohag': 'Sohag',
      'Akhmim': 'Akhmim',
      'Tahta': 'Tahta',
      'Gerga': 'Gerga',
      'El Balyana': 'El Balyana',
      'Dar El Salam': 'Dar El Salam',
      'Asyut': 'Asyut',
      'Faiyum': 'Faiyum',
      '6th of October City': '6th of October City',
      '10th of Ramadan City': '10th of Ramadan City',

      // Cities - Algeria
      'Algiers': 'Algiers',
      'Bab El Oued': 'Bab El Oued',
      'Hydra': 'Hydra',
      'El Harrach': 'El Harrach',
      'Bir Mourad Rais': 'Bir Mourad Rais',
      'Dar El Beida': 'Dar El Beida',
      'Oran': 'Oran',
      'Bir El Djir': 'Bir El Djir',
      'Es Senia': 'Es Senia',
      'Arzew': 'Arzew',
      'Aïn El Turk': 'Aïn El Turk',
      'Constantine': 'Constantine',
      'El Khroub': 'El Khroub',
      'Hamma Bouziane': 'Hamma Bouziane',
      'Didouche Mourad': 'Didouche Mourad',
      'Annaba': 'Annaba',
      'El Bouni': 'El Bouni',
      'El Hadjar': 'El Hadjar',
      'Seraidi': 'Seraidi',
      'Blida': 'Blida',
      'Boufarik': 'Boufarik',
      'Larbaa': 'Larbaa',
      'Meftah': 'Meftah',
      'Batna': 'Batna',
      'Tazoult': 'Tazoult',
      'Arris': 'Arris',
      'Merouana': 'Merouana',
      'Setif': 'Setif',
      'El Eulma': 'El Eulma',
      'Ain Arnat': 'Ain Arnat',
      'Bougaa': 'Bougaa',
      'Bejaia': 'Bejaia',
      'Akbou': 'Akbou',
      'Tichy': 'Tichy',
      'Amizour': 'Amizour',
      'Tlemcen': 'Tlemcen',
      'Maghnia': 'Maghnia',
      'Remchi': 'Remchi',
      'Sebdou': 'Sebdou',
      'Chlef': 'Chlef',
      'Tenes': 'Tenes',
      'El Karimia': 'El Karimia',
      'Oued Fodda': 'Oued Fodda',
      'Skikda': 'Skikda',
      'Azzaba': 'Azzaba',
      'Collo': 'Collo',
      'El Harrouch': 'El Harrouch',
      'Tiaret': 'Tiaret',
      'Sougueur': 'Sougueur',
      'Ain Deheb': 'Ain Deheb',
      'Mostaganem': 'Mostaganem',
      'Ain Nouissy': 'Ain Nouissy',
      'Hassi Mameche': 'Hassi Mameche',
      'Bordj Bou Arreridj': 'Bordj Bou Arreridj',
      'Ras El Oued': 'Ras El Oued',
      'Bir Kasdali': 'Bir Kasdali',
      'Medea': 'Medea',
      'Berrouaghia': 'Berrouaghia',
      'Ksar El Boukhari': 'Ksar El Boukhari',
      'Djelfa': 'Djelfa',
      'Ain Oussera': 'Ain Oussera',
      'Hassi Bahbah': 'Hassi Bahbah',
      'Laghouat': 'Laghouat',
      'Aflou': 'Aflou',
      'Ksar El Hirane': 'Ksar El Hirane',
      'Biskra': 'Biskra',
      'Tolga': 'Tolga',
      'Oumache': 'Oumache',
      'Sidi Okba': 'Sidi Okba',
      'Ouargla': 'Ouargla',
      'Hassi Messaoud': 'Hassi Messaoud',
      'Rouissat': 'Rouissat',
      'Ghardia': 'Ghardia',
      'Berriane': 'Berriane',
      'Metlili': 'Metlili',
      'El Guerrara': 'El Guerrara',
      'Tizi Ouzou': 'Tizi Ouzou',
      'Draa Ben Khedda': 'Draa Ben Khedda',
      'Azazga': 'Azazga',
      'Tigzirt': 'Tigzirt',
      'Boumerdes': 'Boumerdes',
      'Boudouaou': 'Boudouaou',
      'Dellys': 'Dellys',
      'Thenia': 'Thenia',
      'Tipaza': 'Tipaza',
      'Cherchell': 'Cherchell',
      'Hadjout': 'Hadjout',
      'Kolea': 'Kolea',
      'Jijel': 'Jijel',
      'Taher': 'Taher',
      'El Milia': 'El Milia',
      'Saida': 'Saida',
      'Youb': 'Youb',
      'Ain El Hadjar': 'Ain El Hadjar',
      'Mascara': 'Mascara',
      'Sig': 'Sig',
      'Tighennif': 'Tighennif',
      'Relizane': 'Relizane',
      'Oued Rhiou': 'Oued Rhiou',
      'Zemmoura': 'Zemmoura',
      'Tebessa': 'Tebessa',
      'Cheria': 'Cheria',
      'El Aouinet': 'El Aouinet',
      'Souk Ahras': 'Souk Ahras',
      'Sedrata': 'Sedrata',
      'M\'Daourouch': 'M\'Daourouch',
      'El Oued': 'El Oued',
      'Robbah': 'Robbah',
      'Guemar': 'Guemar',
      'Khenchela': 'Khenchela',
      'Kais': 'Kais',
      'Bouhmama': 'Bouhmama',
      'Mila': 'Mila',
      'Chelghoum Laid': 'Chelghoum Laid',
      'Tadjenanet': 'Tadjenanet',
      'Ain Defla': 'Ain Defla',
      'El Attaf': 'El Attaf',
      'Miliana': 'Miliana',
      'Naama': 'Naama',
      'Mecheria': 'Mecheria',
      'Ain Sefra': 'Ain Sefra',
      'El Bayadh': 'El Bayadh',
      'Bougtob': 'Bougtob',
      'El Abiodh Sidi Cheikh': 'El Abiodh Sidi Cheikh',
      'Tamanrasset': 'Tamanrasset',
      'In Salah': 'In Salah',
      'In Guezzam': 'In Guezzam',
      'Adrar': 'Adrar',
      'Reggane': 'Reggane',
      'Timimoun': 'Timimoun',
      'Illizi': 'Illizi',
      'Djanet': 'Djanet',
      'Bechar': 'Bechar',
      'Kenadsa': 'Kenadsa',
      'Abadla': 'Abadla',
      'Tindouf': 'Tindouf',
      'Sidi Bel Abbes': 'Sidi Bel Abbes',
      'El Tarf': 'El Tarf',
      'Ghardaia': 'Ghardaia',
      'could_not_launch_dialer': 'Could not open phone dialer',
      'open_in_maps': 'Open in Maps',
      'could_not_open_maps': 'Could not open Google Maps',
      'select_year': 'Select Year',
      'select_month': 'Select Month',
      'select_day': 'Select Day',
      'january': 'Jan',
      'february': 'Feb',
      'march': 'Mar',
      'april': 'Apr',
      'june': 'Jun',
      'july': 'Jul',
      'august': 'Aug',
      'september': 'Sep',
      'october': 'Oct',
      'november': 'Nov',
      'december': 'Dec',
      'enter_valid_email': 'Enter a valid email',
      'is_required': 'is required',
      'certification_required': 'Please certify the information is correct',
      'select_your_speciality': 'Select your specialty',
      'select_your': 'Select your',
      'select_medical_specialty': 'Select Medical Specialty',
      'unclaimed_earnings': 'Unclaimed Earnings',
      'claim': 'Claim',
      'no_transactions_yet': 'No transactions yet',
      'withdraw_history_desc': 'Your withdraw history will appear here',
      'top_up': 'Top Up',
      'top_up_success_desc': 'Top Up functionality will be available soon',
      'withdraw_success_desc': 'Withdraw functionality will be available soon',
      'top_up_amount': 'Top Up Amount',
      'enter_amount_hint': 'Enter amount (e.g. 50)',
      'invalid_amount': 'Invalid amount',
      'enter_card_details': 'Enter Card Details',
      'card_details': 'Card Details',
      'pay_with_amount': 'Pay @amount',
      'clinic_updated_successfully': 'Clinic updated successfully',
      // Premium Subscription
      'premium_required': 'Premium Subscription Required',
      'premium_required_desc':
          'You are not a premium user. Please upgrade to premium to access all features and enjoy unlimited benefits.',
      'premium_benefits_title': 'Premium Benefits:',
      'premium_benefit_1': '✓ Unlimited AI consultations',
      'premium_benefit_2': '✓ Priority appointment booking',
      'premium_benefit_3': '✓ Exclusive discounts on services',
      'premium_benefit_4': '✓ 24/7 customer support',
      'premium_benefit_5': '✓ Access to premium doctors',
      'payment_details': 'Payment Details',
      'upgrade_to_premium': 'Upgrade to Premium',
      'maybe_later': 'Maybe Later',
      'premium_subscription': 'Premium Subscription',
      'choose_plan': 'Choose Your Plan',
      'monthly_plan': 'Monthly Plan',
      'yearly_plan': 'Yearly Plan',
      'per_month': '/month',
      'per_year': '/year',
      'save_percentage': 'Save @percent%',
      'most_popular': 'Most Popular',
      'subscribe_now': 'Subscribe Now',
      'plan_features': 'Plan Features',
      'subscription_success': 'Subscription Successful!',
      'subscription_success_desc':
          'Welcome to Premium! You now have access to all premium features.',
      'currency_libya': 'LYD',
      'currency_algeria': 'DZD',
      'currency_tunisia': 'TND',
      'currency_egypt': 'EGP',
      'no_earnings_to_claim': 'No earnings to claim',
      'bonus_claimed_success': 'Bonus claimed successfully',
      'failed_to_claim_bonus': 'Failed to claim bonus',
      'share_referral_msg': 'Use my referral code: @code to sign up!',
      'no_referral_code_to_share': 'No referral code available to share',
      'insufficient_balance': 'Insufficient balance to withdraw',
      'withdraw_amount': 'Withdraw Amount',
      'amount_exceeds_balance': 'Amount exceeds available balance',
      'stripe_account_setup': 'Stripe Account Setup',
      'stripe_onboarding_desc':
          'You need to complete your Stripe account setup to withdraw funds. You will be redirected to Stripe to complete the onboarding process.',
      'continue_to_stripe': 'Continue to Stripe',
      'failed_to_generate_onboarding_link':
          'Failed to generate onboarding link',
      'complete_stripe_setup': 'Complete Stripe Setup',
      'stripe_done_desc':
          'After completing your Stripe account setup in the browser, click "Done" to proceed with withdrawal.',
      'failed_to_open_stripe': 'Failed to open Stripe onboarding',
      'withdrawal_success': 'Withdrawal successful',
      'withdrawal_failed': 'Withdrawal failed',
      'appointment_status_updated_to': 'Appointment status updated to',
      'error_updating_status': 'An error occurred while updating status',
      'available_balance': 'Available Balance',
      'done': 'Done',
      'error_occurred_try_again': 'An error occurred, please try again',
      'subscription_information': 'Subscription Information',
      'subscription_status': 'Subscription Status',
      'card_number': 'Card Number',
      'active': 'Active',
      'inactive': 'Inactive',
      'wallet_balance': 'Wallet Balance',
      'amount': 'Amount',
      'top_up_card': 'Top Up Card',
      'prepaid_card_number': 'Prepaid Card Number',
      'enter_card_number': 'Enter card number',
      'top_up_now': 'Top Up Now',
      'card_topped_up_successfully': 'Card topped up successfully',
      'please_enter_card_number': 'Please enter a card number',
      'booking': 'Booking',
      'recharge': 'Recharge',
      'biography': 'Biography',
      'tap_to_select_file': 'Tap to select a file',
      'unable_to_preview_file': 'Unable to preview file',
      'not_uploaded': 'Not uploaded',
      'delete_account': 'Delete Account',
      'confirm_delete_account': 'Are you sure you want to delete your account?',
      'failed_to_delete_account': 'Failed to delete account',
      'search_location': 'Search Location',
      'confirm_location': 'Confirm Location',
      'move_marker_desc': 'Pan map to place marker on exact location',
      'detect_location': 'Detect Location',
    },
    'ar_SA': {
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'next': 'التالي',
      'skip': 'تخطي',
      'login': 'تسجيل الدخول',
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'notification': 'الإشعارات',
      'rewards': 'المكافآت',
      'log_out': 'تسجيل الخروج',
      'dark_theme': 'المظهر الداكن',
      'select_country': 'اختر الدولة',
      'confirm_logout': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'yes': 'نعم',
      'clinic_manager_info': 'معلومات مدير العيادة',
      'manager_full_name': 'الاسم الكامل للمدير',
      'manager_phone_number': 'رقم هاتف المدير',
      'clinic_logo': 'شعار العيادة',
      'upload_logo': 'رفع الشعار',
      'clinic_name': 'اسم العيادة',
      'enter_clinic_name': 'أدخل اسم عيادتك',
      'about_clinic': 'عن العيادة',
      'enter_about_clinic': 'أدخل نبذة عن العيادة',
      'contact_phone_number': 'رقم هاتف التواصل',
      'enter_contact_phone': 'أدخل رقم هاتف التواصل',
      'location_optional': 'الموقع (اختياري)',
      'enter_location': 'أدخل الموقع',
      'contact_number': 'رقم التواصل',
      'submit_create_clinic': 'إرسال وإنشاء العيادة',
      'clinic_review_message': 'شكراً لك. حساب عيادتك قيد المراجعة الآن',
      'clinic_review_desc':
          'يقوم فريقنا بمراجعة تفاصيل عيادتك للحفاظ على سلامة وموثوقية سلامة. بمجرد الموافقة، ستتمكن من إدارة أطبائك ومواعيدك.',
      'submitted_information': 'المعلومات المقدمة',
      'ok_got_it': 'حسناً، فهمت!',
      'professional_info': 'معلوماتك المهنية',
      'select_medical_specialty': 'اختر التخصص الطبي',
      'medical_specialty': 'التخصص الطبي',
      'your_medical_specialty': 'تخصصك الطبي',
      'years_of_experience': 'سنوات الخبرة',
      'enter_years_experience': 'أدخل سنوات الخبرة',
      'license_number_optional': 'رقم الترخيص (اختياري)',
      'enter_license_number': 'أدخل رقم الترخيص الطبي',
      'base_consultation_fee': 'رسوم الاستشارة الأساسية',
      'enter_consultation_fee': 'أدخل رسوم الاستشارة',
      'clinic_info_optional': 'معلومات العيادة (اختياري)',
      'select_clinic': 'اختر العيادة',
      'select_clinic_info': 'اختر معلومات العيادة',
      'complete_profile': 'أكمل ملفك الشخصي',
      'select_gender': 'اختر الجنس',
      'select_your_gender': 'اختر جنسك',
      'select_your_country': 'اختر دولتك',
      'select_city': 'اختر المدينة',
      'select_your_city': 'اختر مدينتك',
      'address_optional': 'العنوان (اختياري)',
      'certification_message': 'أقر بأن جميع المعلومات المقدمة دقيقة وصحيحة.',
      'enter_referral_code_optional': 'أدخل رمز الإحالة (اختياري)',
      'can_skip_step': 'يمكنك تجاوز هذه الخطوة.',
      'referral_code': 'رمز الإحالة',
      'error_fill_fields': 'يرجى ملء جميع الحقول المطلوبة وتصديق المعلومات',
      'profile_info': 'معلومات الملف الشخصي',
      'refer': 'الإحالة',
      'insurance': 'التأمين',
      'country': 'الدولة',
      'help_center': 'مركز المساعدة',
      'legal_and_policies': 'القانونية والسياسات',
      'send_feedback': 'ارسل رأيك',
      'change_country': 'تغيير الدولة',
      'full_name': 'الاسم الكامل',
      'gender': 'الجنس',
      'date_of_birth': 'تاريخ الميلاد',
      'city': 'المدينة',
      'address_details': 'تفاصيل العنوان',
      'male': 'ذكر',
      'patient': 'مريض',
      'libya': 'ليبيا',
      'egypt': 'مصر',
      'syria': 'سوريا',
      'algeria': 'الجزائر',
      'enter_full_name': 'أدخل الاسم الكامل',
      'select_date_of_birth': 'اختر تاريخ ميلادك',
      'address': 'العنوان',
      'enter_address': 'أدخل عنوانك',
      'save_change': 'حفظ التغييرات',
      'female': 'أنثى',
      'riyadh': 'الرياض',
      'jeddah': 'جدة',
      'dammam': 'الدمام',
      'success': 'نجاح',
      'profile_updated_success': 'تم تحديث الملف الشخصي بنجاح',
      'referral_code_submitted': 'تم تقديم رمز الإحالة (أو تم التجاوز)',
      'slogan': 'شريكك الطبي الموثوق',
      'phone_number': 'رقم الهاتف',
      'enter_phone_number': 'أدخل رقم هاتفك',
      'digits': 'أرقام',
      'choose_code_method': 'اختر طريقة استلام الرمز',
      'whatsapp': 'واتساب',
      'sms_code': 'رسالة نصية',
      'continue': 'متابعة',
      'tunisia': 'تونس',
      'please_enter_phone': 'يرجى إدخال رقم الهاتف',
      'phone_9_digits': 'يجب أن يتكون رقم الهاتف من 9 أرقام',
      'phone_8_digits': 'يجب أن يتكون رقم الهاتف من 8 أرقام',
      'phone_10_digits': 'يجب أن يتكون رقم الهاتف من 10 أرقام',
      'phone_min_8_digits': 'يجب أن يتكون رقم الهاتف من 8 أرقام على الأقل',
      'invalid_provider_libya':
          'رمز مزود غير صالح (يجب أن يبدأ بـ 91، 92، 93، 94، 95)',
      'invalid_provider_egypt':
          'رمز مزود غير صالح (يجب أن يبدأ بـ 10، 11، 12، 15)',
      'invalid_provider_algeria': 'رمز مزود غير صالح (يجب أن يبدأ بـ 5، 6، 7)',
      'enter_verification_code': 'أدخل رمز التحقق',
      'verification_code_message':
          'ستتلقى رسالة واتساب تحتوي على رمز التحقق على',
      'didnt_receive_code': 'لم تستلم الرمز؟  ',
      'resend': 'إعادة إرسال',
      'resend_code_in': 'إعادة إرسال الرمز خلال',
      'submit': 'إرسال',
      'enter_6_digits': 'يرجى إدخال 6 أرقام كاملة',
      'choose_your_role': 'اختر دورك',
      'role_selection_subtitle':
          'حدد دور المستخدم قبل المتابعة لإعداد الملف الشخصي',
      'doctor': 'طبيب',
      'clinic': 'عيادة',
      'faq': 'الأسئلة الشائعة',
      'who_is_salama': 'من هو سلامة؟',
      'who_is_salama_desc':
          'سلامة هي منصة رعاية صحية شاملة تربط المرضى بالأطباء المؤهلين للاستشارات والخدمات الطبية.',
      'doctor_consultation_title': 'ما هي استشارة الطبيب؟',
      'doctor_consultation_desc':
          'استشارة الطبيب هي موعد طبي مهني حيث يمكنك مناقشة مخاوفك الصحية وتلقي التشخيص والحصول على توصيات العلاج من مقدمي الرعاية الصحية المؤهلين.',
      'Libya': 'ليبيا',
      'Tunisia': 'تونس',
      'Egypt': 'مصر',
      'Algeria': 'الجزائر',
      'Syria': 'سوريا',
      'schedule_appointment_title': 'كيف يمكنني حجز موعد؟',
      'schedule_appointment_desc':
          'يمكنك حجز موعد عن طريق تصفح الأطباء المتاحين واختيار الفترة الزمنية المفضلة لديك وتأكيد حجزك من خلال التطبيق.',
      'payment_options_title': 'ما هي خيارات الدفع؟',
      'payment_options_desc':
          'نقبل طرق دفع مختلفة بما في ذلك بطاقات الائتمان وبطاقات الخصم وخيارات الدفع عبر الهاتف المحمول لراحتك.',
      'cancel_reschedule_title': 'كيف يمكنني إلغاء أو إعادة جدولة الموعد؟',
      'cancel_reschedule_desc':
          'يمكنك إلغاء أو إعادة جدولة موعدك من قسم المواعيد. يرجى ملاحظة سياسة الإلغاء الخاصة بنا لأي رسوم مطبقة.',
      'referral_program': 'برنامج الإحالة',
      'referral_program_desc': 'ادعُ أصدقاءك واكسب 1 دينار عن كل اشتراك!',
      'your_referral_code': 'رمز الإحالة الخاص بك',
      'friends_invited': 'الأصدقاء المدعوون',
      'total_earned': 'إجمالي الأرباح',
      'terms': 'الشروط',
      'terms_content':
          'نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي .',
      'changes_policies': 'تغييرات في الخدمة و/أو الشروط:',
      'changes_policies_content':
          'نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي نص تجريبي .',
      'find_doctors_hint': 'ابحث عن أطباء، عيادات، تخصصات...',
      'health_ai_assistant': 'مساعد الصحة الذكي',
      'could_not_open_email': 'عذراً، لا يوجد تطبيق بريد إلكتروني مثبت.',
      'ai_assistant_desc': 'اسأل أي شيء عن الأعراض، الأطباء أو العيادات.',
      'ambulance': 'إسعاف',
      'pharmacy': 'صيدلية',
      'consultation': 'استشارة',
      'popular_doctors': 'أطباء مشهورون',
      'view_all': 'عرض الكل',
      'nearby_clinics': 'عيادات قريبة',
      'year_exp': 'سنوات خبرة',
      'years_exp': 'سنة خبرة',
      'neurologist': 'طبيب أعصاب',
      'specialties_count': 'تخصصات',
      'search': 'بحث',
      'book': 'حجز',
      'lyd': 'د.ل',
      'home': 'الرئيسية',
      'appointment': 'الموعد',
      'wallet': 'المحفظة',
      'my_wallet': 'محفظتي',
      'recent_transactions': 'المعاملات الأخيرة',
      'current_balance': 'الرصيد الحالي',
      'balance_desc': 'استخدم رصيدك لدفع المواعيد.',
      'top_up_wallet': 'شحن المحفظة',
      'my_appointment': 'موعدي',
      'queue': 'قائمة الانتظار',
      'review': 'مراجعة',
      'your_review': 'مراجعتك',
      'doctor_details': 'تفاصيل الطبيب',
      'year_of_work': 'سنوات العمل',
      'rating': 'التقييم',
      'per_session': 'لكل جلسة',
      'view_full_timings': 'عرض التوقيت الكامل',
      'about_doctor': 'عن الطبيب',
      'book_appointment': 'حجز موعد',
      'schedule': 'الجدول',
      'day': 'اليوم',
      'time': 'الوقت',
      'to': 'إلى',
      'sunday': 'الأحد',
      'monday': 'الاثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      'choose_time_slot': 'اختر فترة زمنية',
      'select_date_schedule_desc':
          'يرجى اختيار تاريخ أو جدول متاح لإجراء الاستشارة',
      'select_date': 'اختر التاريخ',
      'available_time': 'الوقت المتاح',
      'booking_confirmation': 'تأكيد الحجز',
      'booking_success_desc':
          'تم دفع ثمن موعد طبيبك بنجاح، يرجى الحضور بناءً على الجدول المتفق عليه',
      'back_to_home': 'العودة إلى الرئيسية',
      'confirm_booking': 'تأكيد الحجز',
      'date_time': 'التاريخ والوقت',
      'session_fee': 'رسوم الجلسة',
      'queue_number': 'رقم قائمة الانتظار',
      'payment': 'الدفع',
      'confirm_and_pay': 'تأكيد',
      'select': 'اختر',
      'not_selected': 'لم يتم الاختيار',
      'no_schedule_available': 'لا يوجد جدول متاح',
      'schedule_today': 'جدول اليوم',
      'no_bio_available': 'لا توجد سيرة ذاتية متاحة',
      'no_appointments_found': 'لم يتم العثور على مواعيد',
      'coming_soon': 'قريباً',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      'jul': 'يوليو',
      'aug': 'أغسطس',
      'sep': 'سبتمبر',
      'oct': 'أكتوبر',
      'nov': 'نوفمبر',
      'dec': 'ديسمبر',
      'mon': 'الاثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
      'clinic_details': 'تفاصيل العيادة',
      'info': 'معلومات',
      'read_more': 'اقرأ المزيد',
      'contact': 'اتصال',
      'filter': 'فلتر',
      'reset_filters': 'إعادة ضبط الفلاتر',
      'availability': 'التوفر',
      'price_range': 'نطاق السعر (لكل زيارة)',
      'insurance_accepted': 'التأمين المقبول',
      'minimum_rating': 'الحد الأدنى للتقييم',
      'clear_all': 'مسح الكل',
      'apply_filters': 'تطبيق الفلاتر',
      'most_popular_specialties': 'أشهر التخصصات',
      'results': 'النتائج',
      'specialty': 'التخصص',
      'withdraw': 'سحب',
      'welcome': 'مرحباً',
      'welcome_user': 'مرحباً، @name',
      'total_book': 'إجمالي الحجوزات',
      'today': 'اليوم',
      'upcoming': 'القادمة',
      'todays_appointments': 'مواعيد اليوم',
      'arrived': 'وصل',
      'completed': 'مكتمل',
      'finished': 'منتهي',
      'no_appointments': 'لا توجد مواعيد',
      'notifications': 'الإشعارات',
      'pending': 'قيد الانتظار',
      'in_progress': 'قيد التنفيذ',
      'confirm': 'تأكيد',
      'update_status': 'تحديث الحالة',
      'clinic_info': 'معلومات العيادة',
      'available_times': 'الأوقات المتاحة',
      'select_bank': 'اختر البنك',
      'years': 'سنوات',
      'license_number': 'رقم الترخيص',
      'sar': 'ر.س',
      'enter_address_details': 'أدخل تفاصيل العنوان',
      'enter_specialty': 'أدخل التخصص',
      'enter_years_of_experience': 'أدخل سنوات الخبرة',
      'enter_fee': 'أدخل الرسوم',
      'your_doctor_specialty': 'تخصصك الطبي',
      'tripoli': 'طرابلس',
      'benghazi': 'بنغازي',
      'misrata': 'مصراتة',
      'bank_of_libya': 'مصرف ليبيا',
      'clinic_information': 'معلومات العيادة',
      'working_hours': 'ساعات العمل',
      'location': 'الموقع',
      'na': 'غير متوفر',
      'joined_since': 'انضم منذ',
      'joined_on': 'انضم في',
      'specialists': 'متخصصون',
      'change_clinic': 'تغيير العيادة',
      'choose_a_clinic': 'اختر عيادة',
      'set_your_availability': 'حدد توفرك',
      'select_working_days': 'اختر أيام العمل',
      'set_time_slots': 'حدد فترات الوقت',
      'capacity': 'السعة',
      'add_more': 'إضافة المزيد',
      'need_more_help': 'هل تحتاج إلى مزيد من المساعدة؟',
      'support_team_desc': 'لا تجد ما تبحث عنه؟ فريق الدعم لدينا هنا للمساعدة.',
      'email': 'البريد الإلكتروني',
      'enter_email': 'أدخل البريد الإلكتروني',
      'who_is_nabeel': 'من هو نبيل الجربي؟',
      'who_is_nabeel_desc':
          'نبيل الجربي هي منصة رعاية صحية شاملة تربط المرضى بالأطباء المؤهلين للاستشارات والخدمات الطبية.',
      'doctors': 'الأطباء',
      'copied': 'تم النسخ',
      'referral_code_copied': 'تم نسخ رمز الإحالة إلى الحافظة',
      'consultation_fee': 'رسوم الاستشارة',
      'referral_bonus': 'مكافأة الإحالة',
      'filter_by_doctor': 'تصفية حسب الطبيب',
      'all_doctors': 'جميع الأطباء',
      'queue_label': 'رقم الدور #',
      'new_appointment_booked': 'تم حجز موعد جديد',
      'upcoming_appointment_title': 'موعد قادم',
      'appointments': 'المواعيد',
      'pending_tab': 'قيد الانتظار',
      'in_progress_tab': 'قيد التنفيذ',
      'completed_tab': 'مكتمل',
      'arrived_tab': 'وصل',
      'total_with_count': 'الإجمالي (@count)',
      'show_less': 'عرض أقل',
      'photos': 'الصور',
      'manager_name': 'اسم المدير',
      'manager_number': 'رقم المدير',
      'clinic_number': 'رقم العيادة',
      'edit_clinic_info': 'تعديل معلومات العيادة',
      'add_photo': 'إضافة صورة',
      'referred': 'تمت الإحالة',
      'referral_desc_clinic':
          'ادعُ عيادات أخرى أو مرضى واكسب 50 دينار ليبي مقابل كل إحالة ناجحة!',
      'terms_clinic_title': 'شروط الخدمة للعيادات',
      'terms_clinic_content':
          'من خلال الانضمام إلى سلامة كشريك عيادة، فإنك توافق على تقديم معلومات دقيقة حول خدماتك وأطبائك وتوافرك. أنت مسؤول عن الحفاظ على سرية بيانات اعتماد حسابك وعن جميع الأنشطة التي تحدث تحت حسابك.',
      'privacy_policy': 'سياسة الخصوصية',
      'privacy_policy_clinic_desc':
          'نحن نقدر خصوصيتك وخصوصية مرضاك. يرجى الرجوع إلى سياسة الخصوصية الرئيسية الخاصة بنا للحصول على تفاصيل حول كيفية جمع البيانات واستخدامها وحمايتها داخل المنصة.',
      'delete_specialty': 'حذف التخصص',
      'delete_specialty_confirmation':
          'هل أنت متأكد أنك تريد إزالة هذا التخصص؟',
      'delete': 'حذف',
      'add_specialty': 'إضافة تخصص',
      'search_specialty': 'البحث عن تخصص',
      'clinic_updated_success': 'تم تحديث معلومات العيادة بنجاح',
      'dermatology': 'طب الجلد',
      'dentistry': 'طب الأسنان',
      'psychiatry': 'الطب النفسي',
      'pediatrics': 'طب الأطفال',
      'psychotherapy': 'العلاج النفسي',
      'neurology': 'طب الأعصاب',
      'orthopedics': 'جراحة العظام',
      'obstetrics': 'طب التوليد وأمراض النساء',
      'ear_nose_throat': 'الأذن والأنف والحنجرة',
      'cardiology': 'أمراض القلب والأوعية الدموية',
      'general_surgery': 'الجراحة العامة',
      'ophthalmology': 'طب العيون',
      'urology': 'جراحة المسالك البولية',
      'about_clinic_desc':
          'تلتزم عيادتنا بتقديم خدمات رعاية صحية موثوقة وعالية الجودة مع نهج المريض أولاً. نحن نركز على التشخيص الدقيق والعلاج الحديث والرعاية الرحيمة لضمان أفضل تجربة لكل مريض.',
      'search_doctor': 'بحث عن طبيب...',
      'all_specialties': 'جميع التخصصات',
      'all_insurance': 'جميع التأمينات',
      'all_cities': 'جميع المدن',
      'all_countries': 'جميع الدول',
      'confirmed': 'مؤكد',
      'inprogress': 'قيد التنفيذ',
      'cancelled': 'ملغي',
      'not_shown': 'لم يحضر',
      'unresolved': 'غير محسوم',
      'not_updated': 'لم يتم التحديث',
      'cancel_appointment_title': 'إلغاء الموعد',
      'cancel_appointment_message': 'هل أنت متأكد أنك تريد إلغاء هذا الموعد؟',
      'yes_cancel': 'نعم، إلغاء',
      'update_status_title': 'تحديث الحالة',
      'update_status_arrived_message': 'هل تريد تحديث الحالة إلى وصل؟',
      'yes_update': 'نعم، تحديث',
      'complete_appointment_title': 'إكمال الموعد',
      'complete_appointment_message': 'هل تريد تحديث الحالة إلى مكتمل؟',
      'yes_complete': 'نعم، إكمال',
      'complete': 'إكمال',
      'status_updated_successfully': 'تم تحديث الحالة بنجاح',
      'failed_to_update_status': 'فشل في تحديث الحالة',
      'load_more': 'تحميل المزيد',
      'confirm_appointment_title': 'تأكيد الموعد',
      'confirm_appointment_message': 'هل أنت متأكد أنك تريد تأكيد هذا الموعد؟',
      'inprogress_appointment_title': 'بدء الموعد',
      'inprogress_appointment_message':
          'هل أنت متأكد أنك تريد تعيين هذا الموعد على أنه قيد التنفيذ؟',
      'save_changes': 'حفظ التغييرات',
      'select_working_day': 'اختر يوم العمل',
      'no_insurance_found': 'لم يتم العثور على تأمين',
      'add_insurance': 'إضافة تأمين',
      'insurance_details': 'تفاصيل التأمين',
      'upload_insurance_image': 'تحميل صورة التأمين',
      'error': 'خطأ',
      'failed_to_fetch_working_hours': 'فشل في جلب ساعات العمل',
      'error_fetching_working_hours': 'حدث خطأ أثناء جلب ساعات العمل',
      'location_permission_title': 'سماح بالوصول إلى الموقع',
      'location_permission_message':
          'نحتاج إلى معرفة موقعك لعرض العيادات والأطباء القريبين منك. يرجى السماح بالوصول إلى الموقع في النافذة التالية.',
      'allow': 'سماح',
      'deny': 'رفض',
      'notification_permission_title': 'سماح بالإشعارات',
      'notification_permission_message':
          'نحتاج إلى إذن لإرسال الإشعارات لك لتنبيهك بشأن المواعيد والتحديثات.',
      'app_name': 'سلامة',
      'unknown': 'غير معروف',
      'available': 'متاح',
      'location_info_unavailable': 'معلومات الموقع غير متوفرة',
      'from': 'من',
      'search_result': 'نتائج البحث',
      'book_now': 'احجز الآن',
      'closed': 'مغلق',
      'am': 'ص',
      'pm': 'م',
      'clinic_updated_successfully': 'تم تحديث معلومات العيادة بنجاح',
      'km': 'كم',
      'no_doctors_available': 'لا يوجد أطباء متاحين',
      'no_insurance_data': 'لا توجد بيانات تأمين',
      'not_available': 'غير متوفر',
      'working_hours_saved_successfully': 'تم حفظ ساعات العمل بنجاح',
      'failed_to_save_working_hours': 'فشل في حفظ ساعات العمل',
      'error_occurred_while_saving': 'حدث خطأ أثناء الحفظ',
      'Feature coming soon': 'الميزة قريبًا',
      'cancel_appointment': 'إلغاء الموعد',
      'are_you_sure_cancel': 'هل أنت متأكد أنك تريد إلغاء هذا الموعد؟',
      'no': 'لا',
      'please_select_rating': 'يرجى اختيار التقييم',
      'review_submitted_successfully': 'تم تقديم المراجعة بنجاح',
      'failed_to_submit_review': 'فشل في تقديم المراجعة',
      'error_occurred': 'حدث خطأ ما',
      'appointment_cancelled_successfully': 'تم إلغاء الموعد بنجاح',
      'failed_to_cancel_appointment': 'فشل في إلغاء الموعد',
      'cancel_appointment_confirmation':
          'هل أنت متأكد أنك تريد إلغاء هذا الموعد؟',
      'yes_confirm': 'نعم، تأكيد',
      'mark_as_arrived': 'تحديد كـ "وصل"',
      'confirm_arrival_message':
          'هل أنت متأكد أنك تريد تحديد هذا الموعد كـ "وصل"؟',
      'ive_arrived': 'لقد وصلت',
      'complete_appointment': 'إكمال الموعد',
      'confirm_complete_message':
          'هل أنت متأكد أنك تريد تحديد هذا الموعد كمكتمل؟',
      'appointment_status_updated': 'تم تحديث حالة الموعد بنجاح',
      'consultation_with': 'استشارة مع',
      'unknown_doctor': 'طبيب غير معروف',
      'no_details_found': 'لم يتم العثور على تفاصيل',
      'doctor_id_missing': 'معرف الطبيب مفقود',
      'failed_to_load_doctor_details': 'فشل في تحميل تفاصيل الطبيب',
      'server_error': 'خطأ في الخادم',
      'all': 'الكل',
      'experience': 'الخبرة',
      '1_3_years': '1-3 سنوات',
      '3_5_years': '3-5 سنوات',
      '5_10_years': '5-10 سنوات',
      '10_plus_years': '+10 سنوات',
      'cardiologist': 'طبيب قلب',
      'dentist': 'طبيب أسنان',
      'orthopedic': 'جراحة عظام',
      'total': 'الإجمالي',
      'about': 'عن',
      'specialties': 'التخصصات',
      'no_specialists_found': 'لم يتم العثور على أخصائيين',
      'add_specialist': 'إضافة أخصائي',
      'enter_specialist_details': 'أدخل تفاصيل الأخصائي',
      'please_select_image': 'يرجى اختيار صورة',
      'please_enter_details': 'يرجى إدخال التفاصيل',
      'specialist_added_success': 'تم إضافة الأخصائي بنجاح',
      'failed_to_add_specialist': 'فشل في إضافة الأخصائي',
      'something_went_wrong': 'حدث خطأ ما',
      'no_photos_yet': 'لا توجد صور بعد',
      'add_photos': 'إضافة صور',
      'delete_photos': 'حذف الصور',
      'photos_uploaded_successfully': 'تم رفع الصور بنجاح',
      'failed_to_upload_photos': 'فشل في رفع الصور',
      'photos_deleted_successfully': 'تم حذف الصور بنجاح',
      'failed_to_delete_photos': 'فشل في حذف الصور',
      'clinic_photos': 'صور العيادة',
      'please_enter_insurance_details': 'يرجى إدخال تفاصيل التأمين',
      'please_select_an_image': 'يرجى اختيار صورة',
      'insurance_added_successfully': 'تم إضافة التأمين بنجاح',
      'failed_to_add_insurance': 'فشل إضافة التأمين',
      'select_insurance': 'اختر التأمين',
      'delete_insurance': 'حذف التأمين',
      'delete_insurance_confirmation': 'هل أنت متأكد أنك تريد حذف هذا التأمين؟',
      'insurance_deleted_successfully': 'تم حذف التأمين بنجاح',
      'failed_to_delete_insurance': 'فشل حذف التأمين',
      'select_specialty': 'اختر التخصص',
      'specialist_deleted_success': 'تم حذف الأخصائي بنجاح',
      'failed_to_delete_specialist': 'فشل حذف الأخصائي',
      'failed_to_fetch_specialists': 'فشل في جلب الأخصائيين',
      'please_select_city': 'يرجى اختيار المدينة',
      'profile_updated_successfully': 'تم تحديث الملف الشخصي بنجاح',
      'failed_to_update_profile': 'فشل تحديث الملف الشخصي',
      'failed_to_update_clinic': 'فشل في تحديث معلومات العيادة',
      'remove_doctor': 'إزالة الطبيب',
      'are_you_sure_remove_doctor':
          'هل أنت متأكد أنك تريد إزالة هذا الطبيب من عيادتك؟',
      'doctor_removed_successfully': 'تم إزالة الطبيب بنجاح',
      'failed_to_remove_doctor': 'فشل في إزالة الطبيب',
      'could_not_remove_doctor_id_missing': 'تعذر إزالة الطبيب، المعرف مفقود.',
      'top_up_card': 'شحن البطاقة',
      'prepaid_card_number': 'رقم البطاقة مسبقة الدفع',
      'enter_card_number': 'أدخل رقم البطاقة',
      'top_up_now': 'اشحن الآن',
      'card_topped_up_successfully': 'تم شحن البطاقة بنجاح',
      'please_enter_card_number': 'يرجى إدخال رقم البطاقة',
      'appointment_confirmed_successfully': 'تم تأكيد الموعد بنجاح',
      'failed_to_confirm_appointment': 'فشل في تأكيد الموعد',
      'managing_appointments_title': 'إدارة المواعيد',
      'managing_appointments_desc':
          'يمكن للأطباء عرض المواعيد الواردة، وقبولها أو إعادة جدولتها، وتحديث حالتها (قيد الانتظار، قيد التنفيذ، مكتمل) مباشرة من لوحة التحكم.',
      'update_profile_title': 'تحديث الملف الشخصي',
      'update_profile_desc':
          'حافظ على تحديث ملفك الشخصي بأحدث تخصصاتك وخبراتك ورسوم الاستشارة لجذب المزيد من المرضى.',
      'payments_title': 'المدفوعات والمحفظة',
      'payments_desc':
          'تتبع أرباحك وعرض سجل المعاملات في قسم المحفظة. تتم معالجة المدفوعات بشكل آمن.',
      'technical_support_title': 'الدعم الفني',
      'technical_support_desc':
          'لأي مشاكل متعلقة بالتطبيق أو مساعدة الحساب، يرجى الاتصال بفريق الدعم لدينا عبر البريد الإلكتروني.',
      'doctor_terms_title': 'شروط خدمة الطبيب',
      'doctor_terms_content':
          'من خلال التسجيل كطبيب في سلامة، فإنك توافق على تقديم المشورة الطبية الدقيقة، والحفاظ على سرية المريض، والالتزام بإرشادات السلوك المهني لدينا. أنت مسؤول عن إدارة جدولك ومواعيدك بكفاءة.',
      'doctor_privacy_policy': 'سياسة خصوصية الطبيب',
      'doctor_privacy_policy_desc':
          'نقوم بجمع ومعالجة بياناتك المهنية لربطك بالمرضى. السجلات الطبية للمرضى سرية للغاية ولا يتم مشاركتها إلا لأغراض الاستشارة.',
      'how_to_book_title': 'كيفية حجز موعد',
      'how_to_book_desc':
          'ابحث عن طبيب أو عيادة حسب التخصص أو الموقع، اختر فترة زمنية متاحة، وقم بتأكيد حجزك فوراً.',
      'my_appointments_help_title': 'مواعيدي والسجل',
      'my_appointments_help_desc':
          'عرض مواعيدك القادمة والسابقة في علامة التبويب "مواعيدي". يمكنك التحقق من حالة وتفاصيل كل زيارة.',
      'patient_profile_help_title': 'تحديث المعلومات الشخصية',
      'patient_profile_help_desc':
          'انتقل إلى ملفك الشخصي لتحديث تفاصيلك الشخصية، وتاريخك الطبي، ومعلومات التأمين للحفاظ على حداثة سجلاتك.',
      'patient_support_title': 'دعم المرضى',
      'patient_support_desc':
          'هل تحتاج إلى مساعدة؟ اتصل بفريق الدعم لدينا للمساعدة في الحجوزات، المدفوعات، أو مشاكل التطبيق.',
      'patient_terms_title': 'شروط خدمة المريض',
      'patient_terms_content':
          'باستخدام سلامة كمريض، فإنك توافق على تقديم معلومات صحية دقيقة والالتزام بسياسات الحجز والإلغاء لدينا. نحن ملتزمون بربطك بمقدمي رعاية صحية معتمدين.',
      'patient_privacy_policy': 'سياسة خصوصية المريض',
      'patient_privacy_policy_desc':
          'بياناتك الصحية حساسة وتتم معاملتها بأعلى مستوى من الأمان. نشارك فقط المعلومات الضرورية مع الأطباء الذين تحجز مواعيد معهم.',
      'managing_doctors_title': 'إدارة الأطباء',
      'managing_doctors_desc':
          'إضافة أو إزالة أو تحديث ملفات تعريف الأطباء داخل عيادتك. تأكد من دقة تخصصاتهم وجداولهم لحجوزات المرضى.',
      'clinic_appointments_help_title': 'مواعيد العيادة',
      'clinic_appointments_help_desc':
          'عرض وإدارة جميع المواعيد عبر أطباء عيادتك من لوحة تحكم مركزية.',
      'clinic_profile_update_title': 'تحديث معلومات العيادة',
      'clinic_profile_update_desc':
          'حافظ على تحديث تفاصيل عيادتك، مثل الموقع ومعلومات الاتصال والصور، لجذب المزيد من المرضى.',
      'clinic_payments_help_title': 'الشؤون المالية والمدفوعات',
      'clinic_payments_help_desc':
          'راقب أرباح ومدفوعات عيادتك بأمان من خلال قسم المحفظة المخصص.',
      'no_notifications_found': 'لم يتم العثور على إشعارات',
      'new_appointment_desc': 'حجزت @name موعدًا لـ @date @time',
      'upcoming_appointment_desc': 'لديك موعد مع @name @time_diff',
      'in_minutes': 'خلال @min دقيقة',
      'tomorrow_low': 'غداً',
      'today_low': 'اليوم',
      'ai_chat_title': 'سلامة الذكي',
      'hi_im_your': 'مرحباً، أنا ',
      'medical': ' مساعدك',
      'assistant_excl': 'الطبي!',
      'ai_welcome_desc':
          'يمكنني مساعدتك في فهم أعراضك والتوصية بالأخصائي المناسب. ما هي الأعراض التي تعاني منها؟',
      'medical_disclaimer':
          'إخلاء مسؤولية طبي: يرجى استشارة أخصائي الرعاية الصحية للحصول على المشورة الطبية أو التشخيص أو العلاج. إن سلامة الذكي مخصص لأغراض معلوماتية فقط.',
      'ask': 'اسأل',
      'describe_symptoms_hint': 'صف أعراضك بإيجاز...',
      'clinics': 'العيادات',
      'distance_away': 'كم بعد',
      'limit_complete_message': 'لقد وصلت للحد الأقصى المسموح به اليوم',
      // Specialties
      'Dermatology': 'طب الجلد',
      'Dentistry': 'طب الأسنان',
      'Psychiatry': 'الطب النفسي',
      'Pediatrics': 'طب الأطفال',
      'Psychotherapy': 'العلاج النفسي',
      'Neurology': 'طب الأعصاب',
      'Orthopedics': 'جراحة العظام',
      'Obstetrics and Genecology': 'طب التوليد وأمراض النساء',
      'Ear, Nose and Throat': 'الأذن والأنف والحنجرة',
      'Cardiology and Vascular Disease': 'أمراض القلب والأوعية الدموية',
      // Insurances
      'LIBYA INSURANCE co.': 'شركة ليبيا للتأمين',
      'Al Madar': 'المدار',
      'Takaful': 'تكافل',
      // Cities - Libya
      'Tripoli': 'طرابلس',
      'Janzour': 'جنزور',
      'Tajura': 'تاجوراء',
      'service_fee': 'رسوم الخدمة',
      'Qasr bin Ghashir': 'قصر بن غشير',
      'Benghazi': 'بنغازي',
      'Sidi Khalifa': 'سيدي خليفة',
      'Al Marj': 'المرج',
      'Al Qubbah': 'القبة',
      'Misrata': 'مصراتة',
      'Zliten': 'زليتن',
      'Harawa': 'هراوة',
      'Hun': 'هون',
      'Waddan': 'ودان',
      'Sokna': 'سوكنة',
      'Sirte': 'سرت',
      'Bin Jawad': 'بن جواد',
      'Nofaliya': 'النوفلية',
      'Sabha': 'سبها',
      'Murzuq': 'مرزق',
      'Brak': 'براك',
      'Al Kufra': 'الكفرة',
      'Tazirbu': 'تازربو',
      'Jalu': 'جالو',
      'Derna': 'درنة',
      'Al Bayda': 'البيضاء',
      'Shahhat': 'شحات',
      'Tobruk': 'طبرق',
      'El Gubba': 'القبة',
      'Khoms': 'الخمس',
      'El Hani': 'الهاني',
      'Ajdabiya': 'اجدابيا',
      'Brega': 'بريقة',
      'Marawa': 'مراوة',
      'Gharyan': 'غريان',
      'Yefren': 'يفرن',
      'Mizda': 'مزدة',
      'Zuwara': 'زوارة',
      'Nalut': 'نالوت',
      'Ghadames': 'غدامس',
      'Ghat': 'غات',
      'Ubari': 'اوباري',
      'Sebha': 'سبها',
      'Zawiya': 'الزاوية',
      'Al Khums': 'الخمس',
      'Sabratha': 'صبراتة',
      'Bani Walid': 'بني وليد',
      'Tarhuna': 'ترهونة',
      'Kufra': 'الكفرة',
      'Hon': 'هون',
      'Yafran': 'يفرن',
      'Brak Al-Shati': 'براك الشاطئ',
      'Qatrun': 'القطرون',
      'Riqdalin': 'رقدالين',
      'Al-Ajilat': 'العجيلات',
      'Qara Buli': 'قرة بوللي',
      'Tokra': 'توكرة',
      'Seluq': 'سلوق',
      'Msallata': 'مسلاتة',
      // Cities - Tunisia
      'Ariana': 'أريانة',
      'La Soukra': 'سكرة',
      'Ezzahra': 'الزهراء',
      'Raoued': 'رواد',
      'Beja': 'باجة',
      'Testour': 'تستور',
      'Nefza': 'نفزة',
      'Tibar': 'تيبار',
      'Ben Arous': 'بن عروس',
      'Hammam Lif': 'حمام الأنف',
      'Rades': 'رادس',
      'Mornag': 'مرناق',
      'Boumhel': 'بومهل',
      'Bizerte': 'بنزرت',
      'Menzel Bourguiba': 'منزل بورقيبة',
      'Ras Jebel': 'رأس الجبل',
      'Sejnane': 'سجنان',
      'Gabes': 'قابس',
      'Matmata': 'مطماطة',
      'Medenine': 'مدنين',
      'El Hamma': 'الحامة',
      'Gafsa': 'قفصة',
      'Metlaoui': 'المتلوي',
      'Redeyef': 'الرديف',
      'Mdhilla': 'المظيلة',
      'Jendouba': 'جندوبة',
      'Aïn Draham': 'عين دراهم',
      'Ghardimaou': 'غار الدماء',
      'Tabarka': 'طبرقة',
      'Kairouan': 'القيروان',
      'Chebika': 'الشبيكة',
      'Haffouz': 'حفوز',
      'Sbikha': 'السبيخة',
      'Kasserine': 'القصرين',
      'Sbeitla': 'سبيطلة',
      'Thala': 'تالة',
      'Foussana': 'فوسانة',
      'Kebili': 'قبلي',
      'Douz': 'دوز',
      'El Faouar': 'الفوار',
      'Mahdia': 'المهدية',
      'Chebba': 'الشابة',
      'Ksour Essef': 'قصور الساف',
      'El Jem': 'الجم',
      'Manouba': 'منوبة',
      'Mornaguia': 'المرناقية',
      'Borj El Amri': 'برج العامري',
      'Zarzis': 'جرجيس',
      'Ben Gardane': 'بن قردان',
      'Houmt Souk': 'حومة السوق',
      'Monastir': 'المنستير',
      'Sahline': 'الساحلين',
      'Moknine': 'المكنين',
      'Bekalta': 'البقالطة',
      'Nabeul': 'نابل',
      'Hammamet': 'الحمامات',
      'Korba': 'قربة',
      'Kelibia': 'قليبية',
      'Sfax': 'صفاقس',
      'Skhira': 'الصخيرة',
      'Thyna': 'طينة',
      'El Ain': 'العين',
      'Sidi Bouzid': 'سيدي بوزيد',
      'Regueb': 'الرقاب',
      'Meknassy': 'المكناسي',
      'Bir El Hafey': 'بئر الحفي',
      'Siliana': 'سليانة',
      'Bouarada': 'بوعرادة',
      'Kesra': 'كسرى',
      'Gaafour': 'قعفور',
      'Sousse': 'سوسة',
      'Hammam Sousse': 'حمام سوسة',
      'Enfidha': 'النفيضة',
      'Akouda': 'أكودة',
      'Tataouine': 'تطاوين',
      'Dehiba': 'الذهيبة',
      'Bir Lahmar': 'بئر الأحمر',
      'Tozeur': 'توزر',
      'Degache': 'دغاش',
      'Hazoua': 'حزوة',
      'Tunis': 'تونس',
      'La Marsa': 'المرسى',
      'Le Kram': 'الكرم',
      'Carthage': 'قرطاج',
      'El Menzah': 'المنزه',
      'Sidi Bou Said': 'سيدي بوسعيد',
      'Zaghouan': 'زغوان',
      'Nadhour': 'الناظور',
      'Bir Mcherga': 'بئر مشارقة',
      'Fahs': 'الفحص',
      'Djerba': 'جربة',
      'Djerjis': 'جرجيس',
      'El Kef': 'الكاف',
      'Gabès': 'قابس',
      'Ramada': 'رمادة',

      // Cities - Egypt
      'Cairo': 'القاهرة',
      'New Cairo': 'القاهرة الجديدة',
      'Nasr City': 'مدينة نصر',
      'Heliopolis': 'مصر الجديدة',
      'Maadi': 'المعادي',
      'Shubra': 'شبرا',
      'Helwan': 'حلوان',
      'Ain Shams': 'عين شمس',
      'Mokattam': 'المقطم',
      'Giza': 'الجيزة',
      '6th of October': '6 أكتوبر',
      'Sheikh Zayed': 'الشيخ زايد',
      'Hawamdeya': 'الحوامدية',
      'Al Ayyat': 'العياط',
      'Saf': 'الصف',
      'Abu Nomros': 'أبو النمرس',
      'Alexandria': 'الإسكندرية',
      'Borg El Arab': 'برج العرب',
      'New Borg El Arab': 'برج العرب الجديدة',
      'Amreya': 'العامرية',
      'Montaza': 'المنتزة',
      'Mansoura': 'المنصورة',
      'Talkha': 'طلخا',
      'Mit Ghamr': 'ميت غمر',
      'Dikirnis': 'دكرنس',
      'Belqas': 'بلقاس',
      'Sherbin': 'شربين',
      'Hurghada': 'الغردقة',
      'Safaga': 'سفاجا',
      'Quseir': 'القصير',
      'Marsa Alam': 'مرسى علم',
      'Ras Ghareb': 'رأس غارب',
      'Damanhur': 'دمنهور',
      'Kafr El Dawwar': 'كفر الدوار',
      'Rashid (Rosetta)': 'رشيد',
      'Abu Hummus': 'أبو حمص',
      'Edku': 'إدكو',
      'Fayoum': 'الفيوم',
      'Senours': 'سنورس',
      'Etsa': 'إطسا',
      'Tamiya': 'طامية',
      'Tanta': 'طنطا',
      'El Mahalla El Kubra': 'المحلة الكبرى',
      'Zefta': 'زفتى',
      'Kafr El Zayat': 'كفر الزيات',
      'Samanoud': 'سمنود',
      'Ismailia': 'الإسماعيلية',
      'Fayed': 'فايد',
      'Qantara East': 'القنطرة شرق',
      'Qantara West': 'القنطرة غرب',
      'Shibin El Kom': 'شبين الكوم',
      'Sadat City': 'مدينة السادات',
      'Menouf': 'منوف',
      'Ashmoun': 'أشمون',
      'Quesna': 'قويسنا',
      'Minya': 'المنيا',
      'Mallawi': 'ملوي',
      'Samalut': 'سمالوط',
      'Beni Mazar': 'بني مزار',
      'Maghagha': 'مغاغة',
      'Banha': 'بنها',
      'Qalyub': 'قليوب',
      'Shubra El Kheima': 'شبرا الخيمة',
      'El Khanka': 'الخانكة',
      'Kafr Shukr': 'كفر شكر',
      'Kharga': 'الخارجة',
      'Dakhla': 'الداخلة',
      'Farafra': 'الفرافرة',
      'Balat': 'بلاط',
      'Suez': 'السويس',
      'Arbaeen': 'الأربعين',
      'Faisal': 'فيصل',
      'Aswan': 'أسوان',
      'Kom Ombo': 'كوم أمبو',
      'Edfu': 'إدفو',
      'Darna': 'دراو',
      'Assiut': 'أسيوط',
      'Dairut': 'ديروت',
      'Manfalut': 'منفلوط',
      'Abnub': 'أبنوب',
      'Abu Tig': 'أبو تيج',
      'Beni Suef': 'بني سويف',
      'Nasser': 'ناصر',
      'Ehnasia': 'إهناسيا',
      'Al Fashn': 'الفشن',
      'Biba': 'ببا',
      'Port Said': 'بورسعيد',
      'Port Fouad': 'بورفؤاد',
      'Damietta': 'دمياط',
      'New Damietta': 'دمياط الجديدة',
      'Ras El Bar': 'رأس البر',
      'Faraskur': 'فارسكور',
      'Zagazig': 'الزقازيق',
      '10th of Ramadan': 'العاشر من رمضان',
      'Belbeis': 'بلبيس',
      'Abu Kabir': 'أبو كبير',
      'Minya Al Qamh': 'منيا القمح',
      'Hehia': 'ههيا',
      'Sharm El Sheikh': 'شرم الشيخ',
      'Dahab': 'دهب',
      'Nuweiba': 'نويبع',
      'Taba': 'طابا',
      'El Tor': 'الطور',
      'Kafr El Sheikh': 'كفر الشيخ',
      'Desouk': 'دسوق',
      'Baltim': 'بلطيم',
      'Sidi Salem': 'سيدي سالم',
      'Fuwa': 'فوه',
      'Marsa Matruh': 'مرسى مطروح',
      'El Alamein': 'العلمين',
      'Siwa': 'سيوة',
      'Sallum': 'السلوم',
      'Dabaa': 'الضبعة',
      'Luxor': 'الأقصر',
      'Esna': 'إسنا',
      'Armant': 'أرمنت',
      'Toud': 'الطود',
      'Qena': 'قنا',
      'Nag Hammadi': 'نجع حمادي',
      'Qift': 'قفط',
      'Naqada': 'نقادة',
      'Dishna': 'دشنا',
      'Abu Tesht': 'أبو تشت',
      'El Arish': 'العريش',
      'Sheikh Zuweid': 'الشيخ زويد',
      'Rafah': 'رفح',
      'Bir Al Abd': 'بئر العبد',
      'Sohag': 'سوهاج',
      'Akhmim': 'أخميم',
      'Tahta': 'طهطا',
      'Gerga': 'جرجا',
      'El Balyana': 'البلينا',
      'Dar El Salam': 'دار السلام',
      'Asyut': 'أسيوط',
      'Faiyum': 'الفيوم',
      '6th of October City': 'مدينة 6 أكتوبر',
      '10th of Ramadan City': 'مدينة 10 رمضان',

      // Cities - Algeria
      'Algiers': 'الجزائر',
      'Bab El Oued': 'باب الواد',
      'Hydra': 'حيدرة',
      'El Harrach': 'الحراش',
      'Bir Mourad Rais': 'بئر مراد رايس',
      'Dar El Beida': 'الدار البيضاء',
      'Oran': 'وهران',
      'Bir El Djir': 'بئر الجير',
      'Es Senia': 'السانية',
      'Arzew': 'أرزيو',
      'Aïn El Turk': 'عين الترك',
      'Constantine': 'قسنطينة',
      'El Khroub': 'الخروب',
      'Hamma Bouziane': 'حامة بوزيان',
      'Didouche Mourad': 'ديدوش مراد',
      'Annaba': 'عنابة',
      'El Bouni': 'البوني',
      'El Hadjar': 'الحجار',
      'Seraidi': 'سرايدي',
      'Blida': 'البليدة',
      'Boufarik': 'بوفاريك',
      'Larbaa': 'الأربعاء',
      'Meftah': 'مفتاح',
      'Batna': 'باتنة',
      'Tazoult': 'تازولت',
      'Arris': 'أريس',
      'Merouana': 'مروانة',
      'Setif': 'سطيف',
      'El Eulma': 'العلمة',
      'Ain Arnat': 'عين أرنات',
      'Bougaa': 'بوقاعة',
      'Bejaia': 'بجاية',
      'Akbou': 'أقبو',
      'Tichy': 'تيشي',
      'Amizour': 'أمزور',
      'Tlemcen': 'تلمسان',
      'Maghnia': 'مغنية',
      'Remchi': 'الرمشي',
      'Sebdou': 'سبدو',
      'Chlef': 'الشلف',
      'Tenes': 'تنس',
      'El Karimia': 'الكريمية',
      'Oued Fodda': 'وادي الفضة',
      'Skikda': 'سكيكدة',
      'Azzaba': 'عزابة',
      'Collo': 'القل',
      'El Harrouch': 'الحروش',
      'Tiaret': 'تيارت',
      'Sougueur': 'السوقر',
      'Ain Deheb': 'عين الذهب',
      'Mostaganem': 'مستغانم',
      'Ain Nouissy': 'عين نويسي',
      'Hassi Mameche': 'حاسي مفسوخ',
      'Bordj Bou Arreridj': 'برج بوعريريج',
      'Ras El Oued': 'رأس الوادي',
      'Bir Kasdali': 'بئر قاصد علي',
      'Medea': 'المدية',
      'Berrouaghia': 'البرواقية',
      'Ksar El Boukhari': 'قصر البخاري',
      'Djelfa': 'الجلفة',
      'Ain Oussera': 'عين وسارة',
      'Hassi Bahbah': 'حاسي بحبح',
      'Laghouat': 'الأغواط',
      'Aflou': 'أفلو',
      'Ksar El Hirane': 'قصر الحيران',
      'Biskra': 'بسكرة',
      'Tolga': 'طولقة',
      'Oumache': 'أوماش',
      'Sidi Okba': 'سيدي عقبة',
      'Ouargla': 'ورقلة',
      'Hassi Messaoud': 'حاسي مسعود',
      'Rouissat': 'الرويسات',
      'Ghardia': 'غرداية',
      'Berriane': 'بريان',
      'Metlili': 'متليلي',
      'El Guerrara': 'القرارة',
      'Tizi Ouzou': 'تيزي وزو',
      'Draa Ben Khedda': 'ذراع بن خدة',
      'Azazga': 'عزازقة',
      'Tigzirt': 'تيقزيرت',
      'Boumerdes': 'بومرداس',
      'Boudouaou': 'بودواو',
      'Dellys': 'دلس',
      'Thenia': 'الثنية',
      'Tipaza': 'تيبازة',
      'Cherchell': 'شرشال',
      'Hadjout': 'حجوط',
      'Kolea': 'القليعة',
      'Jijel': 'جيجل',
      'Taher': 'الطاهير',
      'El Milia': 'الميلية',
      'Saida': 'سعيدة',
      'Youb': 'يوب',
      'Ain El Hadjar': 'عين الحجر',
      'Mascara': 'معسكر',
      'Sig': 'سيق',
      'Tighennif': 'تيغنيف',
      'Relizane': 'غليزان',
      'Oued Rhiou': 'وادي ارهيو',
      'Zemmoura': 'زمورة',
      'Tebessa': 'تبسة',
      'Cheria': 'الشريعة',
      'El Aouinet': 'العوينت',
      'Souk Ahras': 'سوق أهراس',
      'Sedrata': 'سدراتة',
      'M\'Daourouch': 'مداوروش',
      'El Oued': 'الوادي',
      'Robbah': 'الرباح',
      'Guemar': 'قمار',
      'Khenchela': 'خنشلة',
      'Kais': 'قايس',
      'Bouhmama': 'بوحمامة',
      'Mila': 'ميلة',
      'Chelghoum Laid': 'شلغوم العيد',
      'Tadjenanet': 'تاجنانت',
      'Ain Defla': 'عين الدفلى',
      'El Attaf': 'العطاف',
      'Miliana': 'مليانة',
      'Naama': 'النعامة',
      'Mecheria': 'المشرية',
      'Ain Sefra': 'عين الصفراء',
      'El Bayadh': 'البيض',
      'Bougtob': 'بوقطب',
      'El Abiodh Sidi Cheikh': 'الأبيض سيدي الشيخ',
      'Tamanrasset': 'تمنراست',
      'In Salah': 'عين صالح',
      'In Guezzam': 'عين قزام',
      'Adrar': 'أدرار',
      'Reggane': 'رقان',
      'Timimoun': 'تيميمون',
      'Illizi': 'إليزي',
      'Djanet': 'جانت',
      'Bechar': 'بشار',
      'Kenadsa': 'القنادسة',
      'Abadla': 'العبادلة',
      'Tindouf': 'تندوف',
      'Sidi Bel Abbes': 'سيدي بلعباس',
      'El Tarf': 'الطارف',
      'Ghardaia': 'غرداية',
      'could_not_launch_dialer': 'تعذر فتح تطبيق الهاتف',
      'open_in_maps': 'فتح في الخرائط',
      'could_not_open_maps': 'تعذر فتح خرائط جوجل',
      'select_year': 'اختر السنة',
      'select_month': 'اختر الشهر',
      'select_day': 'اختر اليوم',
      'january': 'ينا',
      'february': 'فبر',
      'march': 'مار',
      'april': 'أبر',
      'june': 'يون',
      'july': 'يول',
      'august': 'أغس',
      'september': 'سبت',
      'october': 'أكت',
      'november': 'نوف',
      'december': 'ديس',
      'enter_valid_email': 'أدخل بريد إلكتروني صالح',
      'is_required': 'مطلوب',
      'certification_required': 'يرجى الإقرار بصحة المعلومات',
      'select_your': 'اختر',
      'select_your_speciality': 'اختر تخصصك',
      'unclaimed_earnings': 'الأرباح غير المطالب بها',
      'claim': 'مطالبة',
      'no_transactions_yet': 'لا توجد معاملات بعد',
      'withdraw_history_desc': 'سيظهر سجل السحب الخاص بك هنا',
      'top_up': 'شحن الرصيد',
      'top_up_success_desc': 'ستتوفر ميزة شحن الرصيد قريباً',
      'withdraw_success_desc': 'ستتوفر ميزة السحب قريباً',
      'top_up_amount': 'مبلغ شحن الرصيد',
      'enter_amount_hint': 'أدخل المبلغ (مثلاً 50)',
      'invalid_amount': 'مبلغ غير صالح',
      'enter_card_details': 'أدخل تفاصيل البطاقة',
      'card_details': 'تفاصيل البطاقة',
      'pay_with_amount': 'دفع @amount',
      // Premium Subscription
      'premium_required': 'يتطلب اشتراك بريميوم',
      'premium_required_desc':
          'أنت لست مستخدم بريميوم. يرجى الترقية إلى بريميوم للوصول إلى جميع الميزات والاستمتاع بفوائد غير محدودة.',
      'premium_benefits_title': 'مزايا البريميوم:',
      'premium_benefit_1': '✓ استشارات ذكاء اصطناعي غير محدودة',
      'premium_benefit_2': '✓ أولوية في حجز المواعيد',
      'premium_benefit_3': '✓ خصومات حصرية على الخدمات',
      'premium_benefit_4': '✓ دعم العملاء على مدار الساعة',
      'premium_benefit_5': '✓ الوصول إلى الأطباء المميزين',
      'payment_details': 'تفاصيل الدفع',
      'upgrade_to_premium': 'الترقية إلى بريميوم',
      'maybe_later': 'ربما لاحقاً',
      'premium_subscription': 'اشتراك بريميوم',
      'choose_plan': 'اختر خطتك',
      'monthly_plan': 'خطة شهرية',
      'yearly_plan': 'خطة سنوية',
      'per_month': '/شهر',
      'per_year': '/سنة',
      'save_percentage': 'وفر @percent%',
      'most_popular': 'الأكثر شعبية',
      'subscribe_now': 'اشترك الآن',
      'plan_features': 'ميزات الخطة',
      'subscription_success': 'تم الاشتراك بنجاح!',
      'subscription_success_desc':
          'مرحباً بك في بريميوم! لديك الآن إمكانية الوصول إلى جميع الميزات المميزة.',
      'currency_libya': 'د.ل',
      'currency_algeria': 'د.ج',
      'currency_tunisia': 'د.ت',
      'currency_egypt': 'ج.م',
      'no_earnings_to_claim': 'لا توجد أرباح للمطالبة بها',
      'bonus_claimed_success': 'تمت المطالبة بالمكافأة بنجاح',
      'failed_to_claim_bonus': 'فشل في المطالبة بالمكافأة',
      'share_referral_msg': 'استخدم رمز الإحالة الخاص بي: @code للتسجيل!',
      'no_referral_code_to_share': 'لا يوجد رمز إحالة متاح للمشاركة',
      'insufficient_balance': 'الرصيد غير كافٍ للسحب',
      'withdraw_amount': 'سحب المبلغ',
      'amount_exceeds_balance': 'المبلغ يتجاوز الرصيد المتاح',
      'stripe_account_setup': 'إعداد حساب سترايب',
      'stripe_onboarding_desc':
          'يجب عليك إكمال إعداد حساب سترايب الخاص بك لسحب الأموال. سيتم توجيهك إلى سترايب لإكمال عملية الإعداد.',
      'continue_to_stripe': 'المتابعة إلى سترايب',
      'failed_to_generate_onboarding_link': 'فشل في إنشاء رابط الإعداد',
      'complete_stripe_setup': 'إكمال إعداد سترايب',
      'stripe_done_desc':
          'بعد إكمال إعداد حساب سترايب في المتصفح، انقر على "تم" لمتابعة السحب.',
      'failed_to_open_stripe': 'فشل في فتح إعداد سترايب',
      'withdrawal_success': 'تم السحب بنجاح',
      'withdrawal_failed': 'فشل في عملية السحب',
      'appointment_status_updated_to': 'تم تحديث حالة الموعد إلى',
      'error_updating_status': 'حدث خطأ أثناء تحديث الحالة',
      'available_balance': 'الرصيد المتاح',
      'done': 'تم',
      'error_occurred_try_again': 'حدث خطأ، يرجى المحاولة مرة أخرى',
      'subscription_information': 'معلومات الاشتراك',
      'subscription_status': 'حالة الاشتراك',
      'card_number': 'رقم البطاقة',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'wallet_balance': 'رصيد المحفظة',
      'amount': 'المبلغ',
      'booking': 'حجز',
      'recharge': 'شحن',
      'biography': 'السيرة الذاتية',
      'tap_to_select_file': 'اضغط لاختيار ملف',
      'unable_to_preview_file': 'تعذر معاينة الملف',
      'not_uploaded': 'لم يتم الرفع',
      'delete_account': 'حذف الحساب',
      'confirm_delete_account': 'هل أنت متأكد أنك تريد حذف حسابك؟',
      'failed_to_delete_account': 'فشل في حذف الحساب',
      'search_location': 'البحث عن موقع',
      'confirm_location': 'تأكيد الموقع',
      'move_marker_desc': 'حرّك الخريطة لوضع العلامة على الموقع الدقيق',
      'detect_location': 'تحديد موقعي',
    },
  };
}
